### ISSUE TITLE
curl url issues-requested URL returned error: 404

### ISSUE THREAD

**Issue by shanithkk** [axodotdev/cargo-dist#1020]
## Description
Throwing error while installing released application using the mention url in the release not. 
``` curl: (22) The requested URL returned error: 404 ``` this is due the extension of `.git` with the url.

current url `https://github.com/hugobyte/composer.git/releases/download/v0.0.5/composer-cli-aarch64-apple-darwin.tar.xz`

Expected behaviour:
https://github.com/hugobyte/composer/releases/download/v0.0.5/composer-cli-aarch64-apple-darwin.tar.xz

cargo dist created installer script mentioned url also should changed to expected format

**Comment by mistydemeo** [comment]
Thanks for bringing this to our attention. This is a bug that was introduced in a recent version of cargo-dist; I'm working on a fix.

**Comment by mistydemeo** [comment]
This should be fixed in the new 0.14.1. Thanks again for your report!
