### ISSUE TITLE
not detecting "required-features"

### ISSUE THREAD

**Issue by RandyMcMillan** [axodotdev/cargo-dist#1029]
I had to bypass "required-features"

<img width="748" alt="cargo-dist-requires-features" src="https://github.com/axodotdev/cargo-dist/assets/152159/49807e14-5f53-4b9c-8557-fb4d3c666bda">

**Comment by ashleygwilliams** [comment]
hey @RandyMcMillan - sorry for the delayed response here, we've been having a busy few weeks. if you want to elaborate a bit further on what you'd like to see happen and how we could help with additional features or config we'd be very happy to hear more
