### ISSUE TITLE
[Feature] Add OS dependencies in ci

### ISSUE THREAD

**Issue by woile** [axodotdev/cargo-dist#104]
Hello there! First, thanks for this awesome tool! I did a quick swap of my previous release pipeline with the generated by `cargo dist init --ci=github` and I got this error:

```
Package pango was not found in the pkg-config search path.
```

See [pipeline error](https://github.com/woile/kindle-notes-parser/actions/runs/4096265219/jobs/7063784778) for more.

It is related to the OS dependencies required by the package. I solved it by adding some [steps to the pipeline](https://github.com/woile/kindle-notes-parser/blob/main/.github/workflows/release.yml#L80-L90), and everything worked fine 🎉 

I was wondering if I missed something or the approach I took was okay. In the docs, I see a [configuring-targets](https://github.com/axodotdev/cargo-dist#configuring-targets). It would be nice to be able to add required deps per target os. I couldn't find an issue related, I apologize if it's already there.

For example:

```toml
[profile.dist.target.os.ubuntu]
deps = "libgtk-3-dev"
[profile.dist.target.os.macos]
deps = "cairo"
```

Cheers!

**Comment by Gankra** [comment]
I agree, someone beat you to the punch filing #102 though! :)
