### ISSUE TITLE
failing scheduled rust CI

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/cargo-dist#105]
<img width="339" alt="Screen Shot 2023-02-06 at 7 08 01 AM" src="https://user-images.githubusercontent.com/1163554/216979424-28dbe162-bbdd-453c-989d-d3c13a02f4cc.png">

```
test (ubuntu-latest, nightly)internal compiler error: no errors encountered even though `delay_span_bug` issued
--
[test (ubuntu-latest, nightly)](https://github.com/axodotdev/cargo-dist/actions/runs/4101278991/jobs/7072904560#step:5:250)
internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:3469 ~ combine[f819]::stream::{impl#47}::reset), const_param_did: None }) (after phase change to runtime-optimized) at bb0[2]:
```

looks like the action failing is for tests on nightly- we may want to make nightly tests "optional" - its useful to know that they are failing but i don't think we show it as failing as it doesn't affect the functioning of the tool- curious your thoughts, @Gankra ? if you're down i can make a PR to get this goin

**Comment by Gankra** [comment]
I wasn't aware of the optional thing, sure!
