### ISSUE TITLE
Windows build always fails with `failed to find symbols`

### ISSUE THREAD

**Issue by virtualritz** [axodotdev/cargo-dist#107]
The tail of my `Run cargo-dist` step in the `cargo-dist`-generated `release.yml`  always looks like this:

```
   Compiling foo v0.1.3 (D:\a\foo\foo)
    Finished dist [optimized] target(s) in 2m 23s
dist ran successfully
{"error": {"message": "failed to find symbols glyphana for glyphana 0.1.3 (path+file:///D:/a/foo/foo)","severity": "error","causes": [],"labels": [],"related": []}}
jq: error (at <stdin>:1): Cannot iterate over null (null)
uploading...
requires at least 2 arg(s), only received 1
uploaded!
Error: Process completed with exit code 1.
```

I found this error in the source code of `cargo-dist`.  Any pointers how to fix this?

**Comment by Gankra** [comment]
Hmm weird, can you link the task run/repo? The error looks like it wanted the .pdb for your project but couldn't find it...

**Comment by Gankra** [comment]
I think this might be your problem: https://github.com/axodotdev/cargo-dist/issues/122#issuecomment-1428614186

**Comment by virtualritz** [comment]
> I think this might be your problem: https://github.com/axodotdev/cargo-dist/issues/122#issuecomment-1428614186
Cheers!

I do indeed have:
```toml
[profile.release]
strip = true

[profile.dist]
inherits = "release"
```

But if I remove this my release binary is considerably larger. I don't want any unneeded symbols in there. What's the solution?

**Comment by Gankra** [comment]
the next release disables pdb support pending a rework in #136
