### ISSUE TITLE
rustup randomly dies updating itself in CI? (windows-only?)

### ISSUE THREAD

**Issue by fritzrehde** [axodotdev/cargo-dist#108]
When trying to build releases for my rust cli tool https://github.com/fritzrehde/watchbind, I get:
```
info: downloading self-update
error: could not copy file from 'C:\Users\runneradmin\.cargo\bin\rustup-init.exe' to 'C:\Users\runneradmin\.cargo\bin\rustup.exe': Access is denied. (os error 5)
ResourceUnavailable: D:\a\_temp\7f52b54c-ff40-4eed-a91a-8b2bb5e42c67.ps1:2
Line |
   2 |  rustup update stable && rustup default stable
     |                          ~~~~~~~~~~~~~~~~~~~~~
     | Program 'rustup.exe' failed to run: An error occurred trying to start process
     | 'C:\Users\runneradmin\.cargo\bin\rustup.exe' with working directory 'D:\a\watchbind\watchbind'. Access is
     | denied.At D:\a\_temp\7f52b54c-ff40-4eed-a91a-8b2bb5e42c67.ps1:2 char:25 + rustup update stable && rustup default
     | stable +                         ~~~~~~~~~~~~~~~~~~~~~.
```
for the windows build.

**Comment by fritzrehde** [comment]
Hmm, I reran the github action manually and this time cargo-dist failed for the macos build with "Process completed with exit code 255.", but the windows build succeeded. Very strange.

**Comment by Gankra** [comment]
This is the second time someone's reported rustup spuriously failing, we should find out if there's some upstream issue.

**Comment by Gankra** [comment]
this looks like it's maaaaybe https://github.com/rust-lang/rustup/issues/2441

**Comment by Gankra** [comment]
Looks like we can potentially work around this with `--no-self-update`
