### ISSUE TITLE
cargo-dist hosted docs are marked as a "deceptive site"

### ISSUE THREAD

**Issue by jamesmunns** [axodotdev/cargo-dist#1092]
<img width="898" alt="Screenshot 2024-05-24 at 16 13 31" src="https://github.com/axodotdev/cargo-dist/assets/2097964/9759f753-e1b1-4818-960a-d9eacab6eb33">

I was browsing the docs on firefox on OSX, and received this warning. I marked the site personally as "not deceptive", but wanted to make y'all aware.

**Comment by jamesmunns** [comment]
(team seems aware, feel free to close as a dupe if it's tracked elsewhere, I just didn't see it in this repo)

**Comment by ashleygwilliams** [comment]
honestly i appreciate the flag- we'll pin this in the repo for others who might also be seeing this. unclear how long it will take to resolve.

**Comment by ashleygwilliams** [comment]
this seems to have resolved itself. no idea why it happened but am very glad it's over!!
