### ISSUE TITLE
[RFC] multi-tenant release workflow

### ISSUE THREAD

**Issue by Gankra** [axodotdev/cargo-dist#111]
The core of cargo-dist supports the notion of workspaces with multiple binaries -- it will find them all and create individual "Releases" for each one ([see "concepts" for important details on what that means](https://github.com/axodotdev/cargo-dist/#concepts), but it's basically "here's a new version of an application" which contains all the various artifacts like platform-specific binaries).

However as I prototyped out more features I increasingly avoided trying to think about how that semantically works and support for this is consequently very broken.

To try to create a coherent vision/implementation of these multi-tenant workspaces, I would like to introduce a new concept at the top of the hierarchy: The *Announcement*. Whereas before all the Releases were in some sense top-level and independent, they will now be logically part of one unified Announcement, which contains the Releases. This will not change the structure of dist-manifest.json -- the entire object is already The Announcement, I'm just formalizing the notion.

# Things That Should Be Unified

The importance of formalizing this notion is that it's reified in things like Github Releases, since we're currently containing one Github Release containing many cargo-dist Releases. I think this is fine and desirable, but it means some values need to be centralized/shared:

* Every Release needs to agree on the repository url and git-tag is being used for The Announcement to create correct artifact-download URLs
  * currently they all use their own `repository` value and assume the tag is `v{version}` where `version` is the one set in their own Cargo.toml. If any two packages disagree on these values and they're part of the same Announcement one of them is going to get broken URLs!
* A Github Release has only one title and body, so even if there's individual changelogs/tables for each binary they need to be stitched together into some unified form
  * #69 
  * I might still emit "partial" release notes for each binary in the dist-manifest.json, in case another tool wants its own custom stitching
* ci-kind (e.g. "github ci") really needs to be central
* toolchain versions ("use this version of cargo-dist", "use this version of rustc") basically have to be central
* compiler flags varying across packages are a headache, you really want to build the workspace in one shot [for consistency](https://crates.io/crates/cargo-hakari) 
  * Cargo nods to this with [the fact that \[profile\] can only be configured at the root of the workspace](https://doc.rust-lang.org/cargo/reference/profiles.html)
* target-triples being unified is *simpler* but this one will probably have to be weakened eventually
  * does Cargo.toml already have a way to say a binary is platform-specific? I've never seen it in the reference!
  
Notably anything that we agree *must* be centralized should only be sourced from `[workspace.metadata.dist]` and not `[package.metadata.dist]` (maybe we'll still parse them just to emit a warning).

# Smashing The Monolith Announcement

At the same time, always releasing+announcing everything in the workspace at once is... not always viable. You should be able to release+announce only one binary (or package with multiple binaries) . Or you should be able to release them all at once but still with individual announcements.

With cargo-release we can make those two situations be one: just have 1 git tag = 1 Github Release = 1 Announce = 1 Run Of cargo-dist's ci.

I believe by default if you run `cargo release` in a virtual workspace it will push separate commits/tags for each package with the git tag format of `{package-name}-v{version}`. i.e. `cargo-dist-v0.1.0` (although they just changed some defaults here and I'm having trouble keeping the new behaviour straight). ((There's also some fancy stuff with cargo-release's [shared-version flag](https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md) that lets you basically create custom release groups but that's something I'm happy to punt on for now.))

So ideally we have a rule that's like:

* If I see a tag like `v0.1.0` I assume we're releasing/announcing the workspace
* If I see a tag like `blah-blah-v0.1.0` I assume we're releasing/announcing only the package (or binary?) blah-blah

Of course this isn't totally consistent... if you have a non-virtual workspace and cargo-release the root package, it will still get tagged as bare `v0.1.0`. I don't love this behaviour from cargo-release from the perspective of a consumer of the tag, but at worst we can document that you should configure cargo-release.

The other problem is if you have a tag `v0.1.0` and there are packages that don't have that version. Do you only release/announce the ones that match that version? Do you still do them all? What if you see `blah-blah-v0.1.0` but `blah-blah` is on v0.2.0? Do you warn? Error? **Exactly what should be done should ideally be based on the kinds of ways our users use multi-tenant workspaces!**

Assuming this can be made coherent enough, this would be managed by each invocation of cargo-dist taking an optional `--tag=...` flag which would be sourced from the computed git tag (currently handled by taiki-e/create-github-release-action). If this flag isn't set (likely when testing locally) I'll probably emit a diagnostic saying the value I'm assuming for the sake of producing some demo output.

edit: oh also fix #79 in some form so you can blanket tell dist to ignore a package

**Comment by niklaswimmer** [comment]
Let me see if I understood that correctly. An _announcement_ initiates the publication of multiple _releases_. It carries information about what _applications_ should be released and what versions should be used. From there we can deduce the set of _artifacts_ that need to be created, by inspecting the individual releases.

For starters we would support two types of announcements:
1. release all applications with the same version
2. release a specific single application with a version

The most common announcement is probably a Git tag. The parsing of said tag would be implemented in `cargo-dist` and should match the behavior `cargo-release` users would expect.

Because an announcement is used for other "global" information as well, one question is whether we extract this information from Cargo files or the environment. For example the repository url could be obtained by concatenating `GITHUB_SERVER_URL` and `GITHUB_REPOSITORY` in the CI.

We also need to clarify the behavior if the values for those global variables differ between multiple Cargo.toml files. Maybe we even want a different behavior for different variables. I could see us error out on versions but only warn about the repository for example.

Overall, I like the idea if the announcement as the top most level type. It makes sense.
