### ISSUE TITLE
signing: apple codesign

### ISSUE THREAD

**Issue by Gankra** [axodotdev/cargo-dist#1121]
This is an issue for codesigning on apple platforms in a way that is officially recognized and respected by macOS (and I guess iOS and friends). In particular it should prevent [Apple's Gatekeeper](https://support.apple.com/en-ca/guide/security/sec5599b66df/web) from flagging the software as untrusted.

I believe this amounts to:

* [giving Apple 100 bucks](https://developer.apple.com/programs/whats-included/)
* using Apple's [signtool](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html)

I think the biggest question is how to get credentials into GitHub Actions SECRETS. In previous discussion [this blogpost came up](https://gregoryszorc.com/blog/2022/04/25/expanding-apple-ecosystem-access-with-open-source,-multi-platform-code-signing/) but I'm not sure if it's relevant / still valid.

**Comment by mistydemeo** [comment]
With #469, we'll also want to be signing the packages. Both `pkgbuild` and `productbuild` have flags that let you sign the package at creation time, but I need to confirm whether you need to sign the individual executables before packaging them, or if `pkgbuild --sign` also signs the files as a side effect.

**Comment by mistydemeo** [comment]
`codesign`, the CLI tool, is provided with the OS/Xcode as a standard utility. It's fairly straightforward to use. It requires a certificate and Apple developer membership. The only tricky part, honestly, is just making sure the certs are in the system keychain where it expects to find them. There are third party actions to perform this, but it's likely we can just write the logic ourselves.

We may also want to [notarize](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution), which we can perform at the commandline using [notarytool](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow#3087734).

**Comment by mistydemeo** [comment]
Implemented in #1361.
