### ISSUE TITLE
Cannot use system certificates when fetching updater

### ISSUE THREAD

**Issue by mchernicoff** [axodotdev/cargo-dist#1154]
When fetching `axoupdater` for use in the optional "update" feature, `cargo-dist` uses `reqwest` with just the default Mozilla Web PKI certificates, and does not pick up the system certificate store. There should be an option to support using the system certs.

The reason for wanting this is basically that some corporate network security software substitutes certificates with ones managed by the organization, and those substituted certs are rooted in one or more certs in the local system certificate store. If that store isn't picked up, then any request whose certs are substituted will fail certificate validation.

**Comment by Gankra** [comment]
This was fixed a few releases back!
