### ISSUE TITLE
Installer Bash source injection is still insufficient on some distros (Fedora, RHEL-compatibles)

### ISSUE THREAD

**Issue by Colonial-Dev** [axodotdev/cargo-dist#1187]
Related to #547 - on at least Fedora 40 and AlmaLinux 9, the current sourcing injection logic isn't sufficient for non-login Bash shells.

This seems to be due to the RPM family (?)  having a `skel` like this:
```
.bash_logout
.bash_profile
.bashrc
```
While (for example) Debian has one like this:
```
.bash_logout
.bashrc
.profile
```
The current implementation iterates over the list `".bash_profile .bash_login .bashrc"` in order, only editing the first valid file it finds in this list.

With the latter layout, there is no `.bash_profile`, so `.bashrc` is edited and everything works as expected. (`.profile` is also edited, presumably for POSIX? At any rate, I believe Bash picks up on that too for login shells.)

With the former layout, it instead edits `.bash_profile`, which Bash only sources in a login shell. GUI terminal emulators are left high and dry.

It looks like the [intention](https://github.com/axodotdev/cargo-dist/pull/555#discussion_r1387056559) was to copy how `rustup` (which *does* work for Fedora and co.) implements it, but it seems the logic was solely based on the [ZSH handling](https://github.com/rust-lang/rustup/blob/b5d74ac69307de29cee586c779bdb6b3aee7f7af/src/cli/self_update/shell.rs#L193-L206) (which only edits the first file it finds) - the [current Bash handling](https://github.com/rust-lang/rustup/blob/b5d74ac69307de29cee586c779bdb6b3aee7f7af/src/cli/self_update/shell.rs#L147) actually seems to be aware of this pitfall and just blasts `source $HOME/.cargo/env` into `.bash_profile`, `.bash_login` *and* `.bashrc`.

First encountered this in atuinsh/atuin#2235, if that helps. I'll try to write a PR myself, but right now I need to get to bed :sweat_smile:

**Comment by mistydemeo** [comment]
Oh interesting - good catch, thank you! I see you submitted a PR; I'll take a look.
