### ISSUE TITLE
Support generating SHA256 checksums

### ISSUE THREAD

**Issue by rgreinho** [axodotdev/cargo-dist#119]
As a developer I would like to provide the ability to the users to verify the SHA256 checksum of the binaries they download.

This could be done either by creating a file containing the sha256 sums of all the binaries (like [shfmt](https://github.com/mvdan/sh/releases)) or by creating a .sha256 file with the same name as the binary (like [cargo-deny](https://github.com/EmbarkStudios/cargo-deny/releases/tag/0.13.7)).

This behavior should be enabled by default, maybe with a way to opt-out if for some reason developers/packagers don't want/need it.

**Comment by ashleygwilliams** [comment]
e.g. https://github.com/Shopify/javy/blob/main/.github/workflows/build-assets.yml#L102
