### ISSUE TITLE
Can't build zip on Windows because unable to run linkage report

### ISSUE THREAD

**Issue by cdanger** [axodotdev/cargo-dist#1219]
On Windows, when I run `cargo dist build --artifacts local --target x86_64-pc-windows-gnu`, I get this:
```console
building artifacts:
  myapp-x86_64-pc-windows-gnu.zip
  myapp-x86_64-pc-windows-gnu.zip.sha256

building cargo target (x86_64-pc-windows-gnu/dist --workspace)

    Finished dist [optimized] target(s) in 2.35s
  x unable to run linkage report for this type of binary
```
It fails with this error "unable to run linkage report", because the target x86_64-pc-windows-gnu is not supported for this I guess, and I don't get any zip being built :-( .
But how can I skip/ignore this linkage report step and still build the zip anyway ?

**Comment by mistydemeo** [comment]
I've just merged a fix for this; it'll be in our next release.
