### ISSUE TITLE
`upload-manifest` fails with HTTP 404 due to `installer.sh` not being found

### ISSUE THREAD

**Issue by oeb25** [axodotdev/cargo-dist#123]
The `upload-manifest` CI job fails at the very end with the following error message:

```js
uploading...
/home/runner/work/checkr/checkr/target/distrib/installer.sh
/home/runner/work/checkr/checkr/target/distrib/installer.ps1
/home/runner/work/checkr/checkr/target/distrib/installer.sh
/home/runner/work/checkr/checkr/target/distrib/installer.ps1
/home/runner/work/checkr/checkr/target/distrib/installer.sh
/home/runner/work/checkr/checkr/target/distrib/installer.ps1
/home/runner/work/checkr/checkr/target/distrib/installer.sh
/home/runner/work/checkr/checkr/target/distrib/installer.ps1
HTTP 404: Not Found (https://uploads.github.com/repos/team-checkr/checkr/releases/92245243/assets?label=&name=installer.sh)
Error: Process completed with exit code 1.
```

The full run can be found [here](https://github.com/team-checkr/checkr/actions/runs/4165823155/jobs/7209359610#logs).

From [the release draft](https://github.com/team-checkr/checkr/releases/tag/untagged-02ba4d375ee1e013e615), I see that the installers at least one `installer.sh` and `installer.ps1` has been uploaded. Opening up the `installer.sh` I can't immediately tell which binary the installer is for, but only having one leads be to believe that this is related to workspaces and multiple binary targets?

Might be related to #69 and #111.

**Comment by Gankra** [comment]
I'm afraid you're going to need to wait for me completing #115 to fix this, dist doesn't really play well in workspaces with multiple binaries yet.

**Comment by oeb25** [comment]
Not a problem at all! Thanks for all of your work!
