### ISSUE TITLE
Github Actions Build is failing with error 255

### ISSUE THREAD

**Issue by skorfmann** [axodotdev/cargo-dist#124]
The `[upload-artifacts (x86_64-unknown-linux-gnu)` Github Action job is failing with a `255` error message and no detailed logging. The mac / windows builds seem to work fine though.

![Screenshot 2023-02-14 at 16 59 54](https://user-images.githubusercontent.com/136789/218791329-377a8259-4711-456d-9a6f-db3e30bc8f03.png)

- Here's the [job](https://github.com/byt-dev/runtime/actions/runs/4175530000/jobs/7230577271)
- Here's the [release workflow](https://github.com/byt-dev/runtime/blob/979113f722127b6a5682c5fb6eddfd92bae51e54/.github/workflows/release.yml)

**Comment by Gankra** [comment]
hmm yeah not 100% sure what's going wrong there with a quick skim, hopefully this will magically clear up with #115..?

**Comment by Gankra** [comment]
I'm going to tentatively close this because the way we do CI has been completely rewritten, if you're still having trouble once 0.0.3 is cut I'm happy to look at it closer.
