### ISSUE TITLE
Allow specifying executable bundle style

### ISSUE THREAD

**Issue by localcc** [axodotdev/cargo-dist#125]
This is useful when the app only has one executable, so there's no need to pack it into an archive, or you want to choose another bundle option, e.g. `tar.xz` for windows.

This could be accomplished by adding an `--exe-bundle-style` cli argument to the tool with different bundle style options.

**Comment by niklaswimmer** [comment]
Just wanted to note that this is related to #17

I like the option of no bundling at all though, would be useful for simple tools.

**Comment by Gankra** [comment]
definitely a dupe of #17, where I'll write some more notes
