### ISSUE TITLE
Add comment in `release.yml` indicating that the file is autogenerated

### ISSUE THREAD

**Issue by DJDuque** [axodotdev/cargo-dist#1281]
I think it would be beneficial to have a comment right at the beginning of the autogenerated `release.yml` that reads something like:

```
# This file was autogenerated by cargo-dist via the following command:
#    cargo dist generate
```

I think it would be helpful for new contributors of a project that uses `cargo-dist` if the release.yml file had a clear comment like that at the beginning.

Tools like `uv` do something like that in the `requirements.txt` file they generate.

**Comment by ashleygwilliams** [comment]
I think this is a great idea and I'm going to open a PR for it today. Apologies for the delay in response!
