### ISSUE TITLE
macos11 builds being used

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [axodotdev/cargo-dist#1283]
You can see from my release GH Action [here](https://github.com/andrewdavidmackenzie/pigg/actions/runs/10282132160/job/28453171716) that cargo-dist is generating build jobs for macos11.

These jobs are stalled waiting for runners.

But macos-11 runner images are deprecated (see [here](https://github.com/conda-forge/conda-forge.github.io/issues/2067) and elsewhere) and so this won't work.

I don't see in the book or release.yml how I can customize the OS I can use for mac/linux/windows platform?

I recently had to move other cross-platforms project builds to use macos-14, and I would like to do the same here.

**Comment by andrewdavidmackenzie** [comment]
I just found this page in the book: https://opensource.axo.dev/cargo-dist/book/ci/customizing.html?highlight=macos#custom-runners

I see that says macos-12 is the default, but that's not my experience. I haven't customized the runner, and as you can see in links in above comment to GH Actions logs, it's using macos-11

**Comment by andrewdavidmackenzie** [comment]
I'll leave this issue open (but feel free to close it), but I'd suggest you up the default macos runner from macos-11, as they do not work anymore.

**Comment by andrewdavidmackenzie** [comment]
OK. So I changed my Cargo.toml file thus:

```
[workspace.metadata.dist.github-custom-runners]
aarch64-apple-darwin = "macos-14"
x86_64-apple-darwin = "macos-12"
x86_64-unknown-linux-gnu = "ubuntu-latest"
x86_64-pc-windows-msvc = "windows-latest"
```

and merged that PR, then pushed a tag again to trigger a release - but same behaviour:

<img width="317" alt="Screenshot 2024-08-07 at 3 23 36 PM" src="https://github.com/user-attachments/assets/fd816e8c-75a9-4a05-bc04-d4a08c1ccece">

**Comment by Gankra** [comment]
You appear to be running cargo-dist 0.3.0, which is about a year old. Newer cargo-dist versions have increased the minimum runners (just install the latest release and `cargo dist init` again to auto-update/migrate everything).

**Comment by andrewdavidmackenzie** [comment]
I thought I installed it afresh!

I'll check later (will a "cargo dist init" again be OK to update things?).

If not, and it's the old one, my apologies!!

**Comment by andrewdavidmackenzie** [comment]
Indeed! :-( 
cargo-dist 0.19.1 installed!
Sorry for that, I was sure I had installed....

**Comment by andrewdavidmackenzie** [comment]
re-trying. This looks like it might be a small (visual, at least) error...

<img width="717" alt="Screenshot 2024-08-07 at 8 42 53 PM" src="https://github.com/user-attachments/assets/88519923-bd60-4ccd-8122-481875fe3160">
