### ISSUE TITLE
Error: Input required and not supplied: token -- I have the token and I followed the docs?

### ISSUE THREAD

**Issue by gacallea** [axodotdev/cargo-dist#1284]
Hi,

ref: https://opensource.axo.dev/cargo-dist/book/installers/homebrew.html
repo: https://github.com/gacallea/freesound-credits
tap: https://github.com/gacallea/homebrew-tap

I have followed the guide verbatim but I get this error from `release.yml`: `Error: Input required and not supplied: token`

The token is there tho? What am I doing wrong?

<img width="811" alt="Screenshot 2024-08-07 at 3 17 44 PM" src="https://github.com/user-attachments/assets/e7cdfe68-d9b8-41f7-a61a-4405ac088d5e">

<img width="816" alt="Screenshot 2024-08-07 at 3 20 14 PM" src="https://github.com/user-attachments/assets/08c8251c-93a5-4b81-8106-e467abc903af">

**Comment by Gankra** [comment]
That is quite perplexing... best guess from a common confusion I have myself: 

You need to set the HOMEBREW_TAP_TOKEN SECRET on https://github.com/gacallea/freesound-credits and *not* the tap repo. The token gives permission to access that repo *to* freesound-credits, so freesound-credits needs to be the one that has the SECRET set.

If you did in fact set it on the right repo, then my second guess would be "was an empty string accidentally saved? try pasting it again."

Good news: after you fiddle with your secrets you can go to the release workflow run and hit "retry all failed jobs" -- the workflow should pick up from where it left off and everything should finish properly.

**Comment by gacallea** [comment]
hi @Gankra :)

thanks! It was the first case. Tbh the docs could use a little clarity. Can't complain tho!

amazing tool!
