### ISSUE TITLE
linux appimage support?

### ISSUE THREAD

**Issue by Ayush1325** [axodotdev/cargo-dist#1297]
Mostly relevant for GUI apps.

Current ways to package rust apps as appimage:
- https://crates.io/crates/cargo-appimage
- https://crates.io/crates/cargo-packager/0.10.1

**Comment by ashleygwilliams** [comment]
hey @Ayush1325 ! sorry for the delay and thanks so much for kicking this off!! i am gonna talk about this with the team tomorrow and we'll get back to you by early next week at the latest (though hopefully sooner!) with next steps.
