### ISSUE TITLE
System glibc version (`2.17') is too old

### ISSUE THREAD

**Issue by DJDuque** [axodotdev/cargo-dist#1302]
Is there a better place to ask questions? e.g. a forum/discord channel?

Question:

I have no idea how any of this works, or what it means. So I am very happy I can rely on `cargo-dist` handling all this for me :D

I have just started providing pre-built binaries for [my package](https://github.com/ALPHA-g-Experiment/alpha-g/releases). I was only targeting `x86_64-unknown-linux-gnu` (because that is all I need really), but in one of the computers I have access to I got:

```
System glibc version (`2.17') is too old; using musl
ERROR: there isn't a package for x86_64-unknown-linux-musl-static
```
Sure, I fixed this by adding the `x86_64-unknown-linux-musl` target, but my questions are:

1. What determines that glibc version 2.17 is too old? Where does it come from?

    Looking at these rustc [target tiers](https://doc.rust-lang.org/rustc/platform-support.html#tier-1-with-host-tools) it says `glibc 2.17+`.
    And I can compile and install rust without issues.

2. It looks like the installers will check that system libraries required at runtime are present in the system downloading my package?
    Is this right? Is it fair to assume that if installation was successful, then running the binary should just work?
    I couldn't find any documentation about this in the book.

Sorry if the questions above make no sense. I am just learning about these topics :)

**Comment by mistydemeo** [comment]
I think the cause of the confusion here is that there's two different kinds of glibc compatibility at play. Let me try to explain.

> What determines that glibc version 2.17 is too old? Where does it come from?

When Rust says its target is glibc 2.17+, it means it *runs* on Linux versions with at least glibc 2.17 - not that it *produces binaries* which run on at least glibc 2.17.

The minimum glibc requirement is determined by what version of glibc is used at the time the program is built. In our case, that means the minimum glibc for the binaries we produce are determined by what Linux system the cargo-dist build process runs on. We default to running on Ubuntu 20.04, which is the oldest version of Linux provided by GitHub's free/builtin runners, and that version uses glibc 2.31.

> It looks like the installers will check that system libraries required at runtime are present in the system downloading my package?

That's right! We've actually *just* shipped a new release which improves this, and I'm in the process of writing a blog post about it.

**Comment by DJDuque** [comment]
Thanks for the explanation. It now all makes a lot more sense to me.

**Comment by mistydemeo** [comment]
You're welcome! Please let me know if I can help with anything else.
