### ISSUE TITLE
whitespace-clean outputs

### ISSUE THREAD

**Issue by Gankra** [axodotdev/cargo-dist#131]
the generated CI/installers contain a little bit of trailing/mixed whitespace and that's gonna annoy people. I thought i flushed it out but at least the CI still has some :(

**Comment by Gankra** [comment]
maaaaybe fixed on tip, so prerelease-03 should have the fixes? (had a bit of a caching struggle so ended up just pushing)

**Comment by Gankra** [comment]
This is still clearly an issue, I have no idea why running `cargo dist generate-ci` on my machine produces weird mixed line-endings. The inputs are all LF-only, afaict? Unless this is a fucked up "my own tools are hiding line-ending stuff from me" problem.

**Comment by ashleygwilliams** [comment]
@Gankra what editor are you using? (i think it may be a "your tools are hiding stuff" situation)

**Comment by Gankra** [comment]
I used vscode to change all the line endings to LF-only, and inspecting with sublime-text seems to confirm this worked, even downloading raw files from github... but maybe there's something I'm missing?

**Comment by Gankra** [comment]
it's poooossible this is actually fixed on tip but some more boostraps need to settle things?

**Comment by Gankra** [comment]
OH OH THIS WOULD BE SO EVIL

IT'S POSSIBLE THAT GITHUB CI HAS `git config --global core.autocrlf true` SET AND SO THE OFFICIAL BUILDS HAVE THE TEMPLATES REWRITTEN TO HAVE CRLF ENDINGS AAAAAAAA
