### ISSUE TITLE
cross compile aarch64-apple-darwin by default

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/cargo-dist#133]
because this is made dead simple by apple (we need only add the target), i think we should include compiling to aarch64-apple-darwin by default, ahead of any larger cross compilation story (which will require more configuration and tooling)

this plus #82/#100  will bring us to target parity with a lot of folks looking to migrate to using cargo-dist

**Comment by Gankra** [comment]
Some notes on this in #77, as this issue is a logical subtask of it.

**Comment by ashleygwilliams** [comment]
/me nods

my preference would be for us to do this first, since it is very simple and browser detection of arch is something we know how to do. i think the fat binary idea is interesting, but it feels much less impactful and generally more complicated to implement to me than building this target independently, if that makes sense?

**Comment by Gankra** [comment]
oh absolutely, i was just literally linking it for the notes

**Comment by frol** [comment]
For those interested in this issue, I have submitted PR #143 to address this issue.

**Comment by Gankra** [comment]
This prerelease has it: https://github.com/axodotdev/cargo-dist/releases/tag/v0.0.4-prerelease.2
