### ISSUE TITLE
Homebrew publishing: autogenerated formula fails autogenerated tests

### ISSUE THREAD

**Issue by cxreiff** [axodotdev/cargo-dist#1331]
The formulas autogenerated by cargo-dist when publishing to a Homebrew tap have formatting that fails the default Github Actions tests that are created when you run `brew tap-new`. Specifically, they fail the style checks run with `brew style`. 

Apologies if this is out of scope, but given that users will run into this CI failure if they follow the [cargo-dist instructions](https://opensource.axo.dev/cargo-dist/book/installers/homebrew.html) for setting up homebrew releases, I figured I'd open an issue. Similar to [this issue](https://github.com/axodotdev/cargo-dist/issues/810).

Here are the logged failures I personally ran into (first one is fixable user-side, the others are from cargo-dist's template):

```
==> Running TapSyntax#run!
==> brew style cxreiff/tap
==> FAILED
Full style cxreiff/tap output
  Taps/cxreiff/homebrew-tap/Formula/ttysvr.rb:16:5: C: [Correctable] Style/SoleNestedConditional: Consider merging nested conditions into outer if conditions.
      if Hardware::CPU.intel?
      ^^
  Taps/cxreiff/homebrew-tap/Formula/ttysvr.rb:23:20: C: [Correctable] Layout/SpaceInsideHashLiteralBraces: Space inside { missing.
    BINARY_ALIASES = {"aarch64-apple-darwin": {}, "x86_64-apple-darwin": {}, "x86_64-pc-windows-gnu": {}, "x86_64-unknown-linux-gnu": {}}
                     ^
  Taps/cxreiff/homebrew-tap/Formula/ttysvr.rb:23:20: C: [Correctable] Style/MutableConstant: Freeze mutable objects assigned to constants.
    BINARY_ALIASES = {"aarch64-apple-darwin": {}, "x86_64-apple-darwin": {}, "x86_64-pc-windows-gnu": {}, "x86_64-unknown-linux-gnu": {}}
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Taps/cxreiff/homebrew-tap/Formula/ttysvr.rb:23:119: C: [Correctable] Layout/LineLength: Line is too long. [135/118]
    BINARY_ALIASES = {"aarch64-apple-darwin": {}, "x86_64-apple-darwin": {}, "x86_64-pc-windows-gnu": {}, "x86_64-unknown-linux-gnu": {}}
                                                                                                                        ^^^^^^^^^^^^^^^^^
  Taps/cxreiff/homebrew-tap/Formula/ttysvr.rb:23:135: C: [Correctable] Layout/SpaceInsideHashLiteralBraces: Space inside } missing.
    BINARY_ALIASES = {"aarch64-apple-darwin": {}, "x86_64-apple-darwin": {}, "x86_64-pc-windows-gnu": {}, "x86_64-unknown-linux-gnu": {}}
                                                                                                                                        ^
  Taps/cxreiff/homebrew-tap/Formula/ttysvr.rb:41:5: C: [Correctable] Style/IfUnlessModifier: Favor modifier if usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
      if OS.mac? && Hardware::CPU.arm?
      ^^
  Taps/cxreiff/homebrew-tap/Formula/ttysvr.rb:44:5: C: [Correctable] Style/IfUnlessModifier: Favor modifier if usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
      if OS.mac? && Hardware::CPU.intel?
      ^^
  Taps/cxreiff/homebrew-tap/Formula/ttysvr.rb:47:5: C: [Correctable] Style/IfUnlessModifier: Favor modifier if usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
      if OS.linux? && Hardware::CPU.intel?
      ^^
  
  1 file inspected, 9 offenses detected, 9 offenses autocorrectable
```

**Comment by ashleygwilliams** [comment]
hey @cxreiff ! thanks for filing this, we have seen this before- not sure if the requirements changed or not, but would definitely love to not have warnings like this and so would welcome a PR. our resident homebrew expert @mistydemeo can also take a look on monday.  if you're interested in contributing and have any questions- feel free to ask here or hop into our discord! https://discord.gg/hSKqzj9R

**Comment by cxreiff** [comment]
I'll certainly make an attempt- though its a bit hairy as at first glance there appear to be conflicts between how cargo-dist's templating works and how `brew style` reads the final result (e.g. the formatter wants to combine/flatten if-statements, but the different if-statement conditionals depend on template conditions). My question would be (perhaps for the homebrew expert) would you be open to just running `brew style --fix` after generating the template, rather than chasing current and future formatting issues?

**Comment by ashleygwilliams** [comment]
oh! i didn't realize there was a fix command. that actually seems like it'd be the simplest for sure and potentially prevent any future issues (assuming they can be autocorrected). i would definitely be interested in seeing how that worked!
