### ISSUE TITLE
Better errors/linting on command not found

### ISSUE THREAD

**Issue by alexanderjophus** [axodotdev/cargo-dist#1338]
I accidentally used the following for my custom build command

```toml
build-command = ["go build -o example ."]
```

This kept giving me the issue that the command could not be found, but was not telling me exactly what it was looking for. I got confused thinking I had to install Go somewhere specific.

The displayed error was;
```
building generic target (x86_64-apple-darwin via go build -o example .)
  × failed to exec generic build: go build -o example .
  ╰─▶ No such file or directory (os error 2)
```

Possibly suggestions:
- Make the error handling a bit more verbose
- Lint the build command before running it, if the user put a space in the first string, chances are it was this mistake?

**Comment by Gankra** [comment]
Great call, this is super easy to mess up.
