### ISSUE TITLE
rename CARGO_DIST_FORCE_INSTALL_DIR

### ISSUE THREAD

**Issue by Gankra** [axodotdev/cargo-dist#1375]
Specifically support both for a while (forever)?

* minimal version: `FORCE_INSTALL_DIR`
* maybe ideal version: app_name.to_upper_case() + "_FORCE_INSTALL_DIR"

axoupdater interop is an issue here, but if we keep the old env-var working we don't need to deal with it immediately.

**Comment by Gankra** [comment]
Needs to be done in shell and powershell installer

**Comment by Gankra** [comment]
A similar rename should probably happen for the special target env-vars cargo-dist uses to talk to bun scripts (the script pretends a renamed var exists but falls back to the one that actually exists)

**Comment by mistydemeo** [comment]
Option 2 seems ideal to me, and very easy for us to produce something all our environments can agree on. In the short term, I think ideally we should

a) Have the installer respect both variables, and
b) Have axoupdater set both variables.

**Comment by Gankra** [comment]
shipped in 0.22.0
