### ISSUE TITLE
cargo-dist autoselects non-GitHub remote and fails

### ISSUE THREAD

**Issue by SamusAranX** [axodotdev/cargo-dist#1387]
The problem I'm experiencing is this:
```
  × GitHub CI support requires a GitHub repository
  ╰─▶   × Your repository URL https://<not github> couldn't be parsed.
        help: Only GitHub URLs are supported at the moment.
```

The repo in question has two remotes: one `origin` that points at something that's not GitHub and one `github` that *does* point at GitHub.

Is there a way for me to tell cargo-dist to just use the GH remote?

**Comment by SamusAranX** [comment]
I can't find any guidance on what a `dist.toml` file should look like.

I found this: https://opensource.axo.dev/cargo-dist/book/reference/config.html
but no matter what I put in there, `cargo dist init` consistently fails with this error message:
```
  × We encountered an issue trying to read your workspace
  ├─▶   × failed to parse TOML
  │
  ╰─▶ missing field 'build-command'
```

The aforementioned reference page suggests this is optional so I don't understand why it's complaining about it missing.

**Comment by ashleygwilliams** [comment]
hrm that sounds frustrating- and i'm sorry about that. our docs are less than ideal at the moment because we are in a transition period to this new config system that allows niceties like the override i'm suggesting. let me draw up an example real fast (where i either find the same bug as you or can give you a good thing to follow to implement what you need).

the fastest/easiest/probably least ideal thing you could do is update your repository field on your Cargo.toml. but in lieu of that let me sort how i can get this override to work for ya.

**Comment by ashleygwilliams** [comment]
ok! i got it working, but it's a bit gross. here's what i found so you can get it working but i think we'll want to make it a bit easier in the future:

create a `dist-workspace.toml`
```
[workspace]
members = ["cargo:./"]
```

create a `dist.toml`
```
[package]
responsitory = "https://github.com/another/repo"
```

this is a lot to just override the one field, but it should work for you

**Comment by SamusAranX** [comment]
That made the workflow generation work, thank you!

However, the workflow itself is now failing:
<img width="804" alt="image" src="https://github.com/user-attachments/assets/2038e435-a9ec-4865-9ea9-cbdc5c6087f9">

This is the repository: https://github.com/SamusAranX/ffauto-rs
Is this something I can fix on my end?

**Comment by ashleygwilliams** [comment]
I am about to go to dinner right now but I can get back to you tomorrow morning! sorry it's been a bumpy ride but we'll get you over the finish line!

**Comment by SamusAranX** [comment]
No worries! This is a scrunkly personal project, not something corporate or mission-critical 😄

**Comment by SamusAranX** [comment]
I looked at this again and I don't think it's a problem with how my repo is set up.

Whatever `cargo dist build` is generating is lacking whatever the subsequent `jq` call is looking for, making the workflow fail even after the actual builds succeeded.

**Comment by mistydemeo** [comment]
Are you able to share the build artifacts from a build where this occurred?

**Comment by SamusAranX** [comment]
I did some more tests and found out that workflows run just fine with stock settings. (oops)
It only started failing when I added these lines to the `workspace.metadata.dist` section of my `Cargo.toml`:
```toml
# Use ZIP files
unix-archive = ".zip"
windows-archive = ".zip"

# Don't upload a source tarball
source-tarball = false
```

Here are all of the build artifacts that felt relevant:

[artifacts-build-local-aarch64-apple-darwin.zip](https://github.com/user-attachments/files/17040044/artifacts-build-local-aarch64-apple-darwin.zip)
[artifacts-build-local-x86_64-apple-darwin.zip](https://github.com/user-attachments/files/17040045/artifacts-build-local-x86_64-apple-darwin.zip)
[artifacts-build-local-x86_64-pc-windows-msvc.zip](https://github.com/user-attachments/files/17040049/artifacts-build-local-x86_64-pc-windows-msvc.zip)
[artifacts-build-local-x86_64-unknown-linux-gnu.zip](https://github.com/user-attachments/files/17040051/artifacts-build-local-x86_64-unknown-linux-gnu.zip)

If you need anything else, please let me know.

**Comment by mistydemeo** [comment]
I believe I found the bug. Working on a fix now.

**Comment by mistydemeo** [comment]
I've merged a fix for that error; it'll make it in our next release.
