### ISSUE TITLE
Add "minimum supported axoupdater version" checks

### ISSUE THREAD

**Issue by Gankra** [axodotdev/cargo-dist#1392]
While many installer changes can be done in a forward/backward-compatible way with axoupdater, some changes, like #1355, strictly require the installed version of axoupdater to be new enough to be aware of the new behaviour. As such they are dangerous to land without some way to tell cargo-dist users "hey you must update axoupdater".

Given we already use guppy/cargo-metadata, we have dependency info at our fingertips and can in fact complain that you're using an older version of axoupdater.

So this feature amounts to:

* add some constant in cargo-dist that records the minimum supported axoupdater version
* for each distable package, if we see it depends on axoupdater *as a library*, complain if the axoupdater version is < the constant

We don't currently process dependency information so someone will need to write that logic. I'm reasonably familiar with the relevant APIs.

**Comment by mistydemeo** [comment]
Note that we'll need to remove this line to actually calculate the deps: https://github.com/axodotdev/cargo-dist/blob/9415ad8c44d5859ec515746fea63371f4432a150/axoproject/src/rust.rs#L56
