### ISSUE TITLE
Can cargo-dist build a binary from Rust source code standalone?

### ISSUE THREAD

**Issue by guest271314** [axodotdev/cargo-dist#144]
Reading the README this appears to be what I am looking for. I am on a machine with limited RAM and disk space. From my experience installing Rust requires at least 1GB of disk space which I don't currently have. I'm just trying to experiment with building this https://github.com/denoland/roll-your-own-javascript-runtime - without downloading 1GB+ to do that.

**Comment by panekj** [comment]
No, you still need rust and cargo installed to build artifacts.

**Comment by guest271314** [comment]
Thanks!
