### ISSUE TITLE
Extract deserialize_yml to axoasset

### ISSUE THREAD

**Issue by mistydemeo** [axodotdev/cargo-dist#1440]
We have a function in cargo-dist that's essentially a copy of [axoasset](https://github.com/axodotdev/axoasset)'s `deserialize_toml` and `deserialize_json`, but for YAML:

https://github.com/axodotdev/cargo-dist/blob/81ca476c43ca4016ca0a50cc03c32892ec0e63b4/cargo-dist/src/backend/ci/github.rs#L876-L893

It would be great for us to extract it from cargo-dist and get it into axoasset.

**Comment by duckinator** [comment]
The first half of this (adding the implementation to axoasset) is here: https://github.com/axodotdev/axoasset/pull/235

**Comment by duckinator** [comment]
The second half is #1604.
