### ISSUE TITLE
Account for the 'Unreleased' section when parsing release notes

### ISSUE THREAD

**Issue by niklaswimmer** [axodotdev/cargo-dist#145]
#138 added support for using the no-prerelease release notes for prereleases. It would be nice if we account for the 'Unreleased' section as well when parsing, using it as another fallback if no no-prerelease entry is available.

Similar to #142 the title of the release notes should be adjusted to match the actually published version.

**Comment by Gankra** [comment]
Just confirming this isn't a thing parse-changelog supports, and would require us to do some significant upstream work or doing some of our own markdown parsing?

**Comment by niklaswimmer** [comment]
I have not tried it tbh, will do later. But I hope it does because their [header regex](https://docs.rs/parse-changelog/latest/parse_changelog/#versions) includes it.

**Comment by niklaswimmer** [comment]
Can confirm, works like a charm. 

```rust
changelogs["Unreleased"].version == "Unreleased"
```

**Comment by Gankra** [comment]
oh ha! I didn't scroll the regex far enough :)
