### ISSUE TITLE
Error: Couldn't generate main.wxs for <package>'s msi installer for workspace in a sub-folder

### ISSUE THREAD

**Issue by pnehrer** [axodotdev/cargo-dist#1453]
We have a GitHub repository that has no `Cargo.toml` in the root, because the Rust workspace is in a sub-folder.

We do, however, have a `dist-workspace.toml` in the root, which includes the Rust workspace sub-folder in its `members` list.

When running `cargo dist generate --mode msi -v debug --check`, we get an error like:

```
  × Couldn't generate main.wxs for <package>'s msi installer
  ├─▶ The '/Users/pnehrer/git/repository/Cargo.toml' path does not exist
  ╰─▶ /Users/pnehrer/git/repository/Cargo.toml
```

It appears that the tool is looking for Cargo.toml in the repository root, and not in the Rust workspace sub-folder.

FWIW I have a small change that I can propose in a PR, which address this issue.

**Comment by ashleygwilliams** [comment]
With the PR you submitted merged- I *think* this issue should be considered solved! If not, please reopen with more details :) Thanks so much again for contributing!! Out of curiosity we'd love to know what you are releasing with cargo-dist- feel free to join our discord https://discord.gg/RUC4EwG3

**Comment by pnehrer** [comment]
Much appreciated @ashleygwilliams thank you!

**Comment by pnehrer** [comment]
Unfortunately we didn't discover a related issue until now: https://github.com/axodotdev/cargo-dist/pull/1566

@ashleygwilliams should I create another issue?
