### ISSUE TITLE
GitHub CI "host" step fails with latest releases

### ISSUE THREAD

**Issue by rob-p** [axodotdev/cargo-dist#1506]
Hi all,

  I've recently updated from an older cargo-dist (0.18) to the newest (0.24.1).  Unfortunately, now when I prepare a release, cargo dist runs and all of my artifacts build, but the "host" step fails with the following error messages:

<img width="1073" alt="image" src="https://github.com/user-attachments/assets/3f797fa3-b3bc-4866-8dbf-9002d1619ec8">

I am not sure what might be going wrong here (it seems like a permission issue), but I've not changed anything on the repo side. Any idea what might be going wrong?

**Comment by rob-p** [comment]
Sighhh... looks like this was a GitHub issue. Turning it off and then back on again (disabling and then re-enabling integration & services) fixed this.  I really find these kinds of transient breakages in GitHub annoying.  Sorry for the noise!

**Comment by fasterthanlime** [comment]
We've been experiencing more and more instability on the part of GitHub Actions lately.. but a 403 is a new one — we'll keep an ear out for similar problems by others. Glad you could get it sorted out!

**Comment by xixixao** [comment]
I have the same issue, and I can't get it resolved. I tried disabling Actions in repo settings, I tried changing permissions to read and write.
