### ISSUE TITLE
final pass on dist-manifest.json

### ISSUE THREAD

**Issue by Gankra** [axodotdev/cargo-dist#153]
After 0.0.3 we should take dist-manifest stability more seriously, I want to do one last pass for breaking changes we can/should make now that we have a new design.

Off the top my head:

* normalize "artifacts" to be a top level array that Releases simply refer to by id
* remove old per-release "release notes" fields, junk
* ..?

**Comment by ashleygwilliams** [comment]
i think this was closed by #156 but let me know if you have anything left in mind before we close this
