### ISSUE TITLE
Unable to use for library only crate

### ISSUE THREAD

**Issue by endoze** [axodotdev/cargo-dist#1549]
I'm trying to use dist to for announcement only releases on my crate [axum-rails-cookie](https://github.com/endoze/axum-rails-cookie), but currently when running the latest version of dist locally with my crate I continually get an error.

<img width="1151" alt="Screenshot 2024-11-12 at 1 58 12 PM" src="https://github.com/user-attachments/assets/47d9df16-a8f3-4b3d-89d2-d9cda1309bce">

Any guidance with what I'm doing wrong would be greatly appreciated!

**Comment by duckinator** [comment]
dist assumes you're only releasing executable binaries by default, but you can force it to release a library by changing `--tag={version}` to `--tag={name}-{version}`


Can you try `dist plan --tag="axum-rails-cookie-v0.1.0"` and let me know if that works for you?

**Comment by endoze** [comment]
Here's the output as requested, still no dice. I tried both the crate name and the lib name:

<img width="1158" alt="Screenshot 2024-11-12 at 5 20 21 PM" src="https://github.com/user-attachments/assets/a8b0ba0d-6865-423a-983a-a46a2a9aa1eb">

**Comment by duckinator** [comment]
Thanks for trying that. That _should_ have worked, so this definitely looks like a bug. I'm looking into it now; I'll let you know when I have more information.

**Comment by duckinator** [comment]
This should be fixed by #1551.

**Comment by endoze** [comment]
This does indeed fix my issue, thank you very much!
