### ISSUE TITLE
How to attach additional assets to a release build

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [axodotdev/cargo-dist#1564]
I am using cargo-dist successfully (thanks!) for building my cross-platform "host" app
(here: https://github.com/andrewdavidmackenzie/pigg/blob/master/.github/workflows/release.yml)

Accompanying this app, is a binary I build for embedded controllers (Pi Pico).
It's a cross platform build that works already in CI
(here: https://github.com/andrewdavidmackenzie/pigg/blob/master/.github/workflows/build_and_test.yml#L103)

When I push a tag and a release is created and binaries attached to it 
(like: https://github.com/andrewdavidmackenzie/pigg/releases/tag/0.4.0)

I would also like to attach a downloadable UF2 file for the microcontroller, that works with that version of the app.

How can I extend the cargo-dist build with this custom step ("make uf2") to create the .uf2 file and then attach it as an asset?

If not possible within cargo-dist workflow, is there some way I can trigger a separate workflow after it, or on the release creation that does the build of the uf2 and adds it as an asset?

Thanks for your help!

**Comment by duckinator** [comment]
I think what you want is the [`extra-artifacts` field in dist-workspace.toml](https://opensource.axo.dev/cargo-dist/book/reference/config.html#extra-artifacts).

Assuming the command is `make uf2` and the output is `some-file.uf2`, you should be able to do:

```
[[dist.extra-artifacts]]
artifacts = ["some-file.uf2"]
build = ["make", "uf2"]
```

This requires a relative file path, I believe relative to the `dist-workspace.toml`.

Let me know if you run into any issues!

**Comment by duckinator** [comment]
Yes, correct on both counts: most dist config got moved to `dist-workspace.toml`, and that is where the above chunk should go.

**Comment by andrewdavidmackenzie** [comment]
Thanks.
I'll try and release soon and see how it goes. Feel free to close the issue if you want.
I guess with that syntax I could not add another extra artifact with a different build command?
(I have one pending to add to the release - but so far I have only been able to build it using "cross")

**Comment by andrewdavidmackenzie** [comment]
Thanks!

**Comment by andrewdavidmackenzie** [comment]
The second artifact I wanted to add was in fact a different musl build for armv.... 

After getting it to work on linux with cargo and macos with cross, I decided to try adding that target directly to a release via cargo dist.

Not sure why it was failing as I install the same linker.

I noticed that release.yml workflow specifies to build on "ubuntu-20.04", and wondered if that could be part of the issue?
Any reason doesn't run on 24.04 or ubuntu-latest?



dist-workspace: https://github.com/andrewdavidmackenzie/pigg/blob/master/dist-workspace.toml

Linker Spec: https://github.com/andrewdavidmackenzie/pigg/blob/master/.cargo/config.toml#L8
(to my slight surprise, this works fine on linux despite not being specific to musl).

Yaml to install arm linkers: https://github.com/andrewdavidmackenzie/pigg/blob/master/.github/install-arm-linkers.yml

Failing Release Build : https://github.com/andrewdavidmackenzie/pigg/actions/runs/11913755115/job/33200173175#logs

**Comment by andrewdavidmackenzie** [comment]
Sorry to continue here, but fixing the above allowed my release workflow to get to the artifacts step and fail there due to my additional one:

"building extra artifacts target (via cd porky && make uf2)
  × failed to exec build: cd
  ╰─▶ No such file or directory (os error 2)
  "

https://github.com/andrewdavidmackenzie/pigg/actions/runs/11916657502/job/33210707341

I guess to do in a subdir I can just put all of it in one string?

**Comment by andrewdavidmackenzie** [comment]
https://opensource.axo.dev/cargo-dist/book/reference/config.html?highlight=artifacts#extra-artifacts 

seems to suggest it's running in project root, as I see relative paths to "target/..." in there....

**Comment by duckinator** [comment]
@andrewdavidmackenzie `cd` likely won't work in this context because it's a shell builtin.

Fortunately, `make` provides a workaround: Make's `-C` flag will change to that directory before doing anything else.

So you probably want this:

```
build = [""make", "-C", "porky", "uf2"]
```

**Comment by andrewdavidmackenzie** [comment]
That makes sense. Either that or wrap it in a shell invocation I guess.

**Comment by andrewdavidmackenzie** [comment]
That makes sense. Either that or wrap it in a shell invocation I guess.

**Comment by andrewdavidmackenzie** [comment]
Thanks for your help! 

I assumed the path was wrong and never thought of the builtin problem, misled by the "No such file or directory (os error 2)"

All working now, and I was able to get the 0.5.0 release of pigg out the door at last!
