### ISSUE TITLE
Error building Windows installer when package is in a subfolder

### ISSUE THREAD

**Issue by pnehrer** [axodotdev/cargo-dist#1591]
When building the Windows installer, we're getting an error stating that the package's Cargo.toml cannot be found in the root workspace directory; however, our package is in a sub-directory.

This is related to https://github.com/axodotdev/cargo-dist/issues/1453, where I missed the case when the package gets actually built.

Proposed PR: https://github.com/axodotdev/cargo-dist/pull/1566

**Comment by mistydemeo** [comment]
Should be fixed by #1566 - thanks!
