### ISSUE TITLE
"already init" is too(?) eager

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/cargo-dist#161]
to migrate to a new version i deleted my cargo.toml dist profile and then ran `cargo dist init` not passing the `--ci=github` flag and was stumped about it not generating my github, so i ran again with the flag and got the "already init!" error. so i had to go delete the profile and run it again. i imagine we could improve this experience.

**Comment by Gankra** [comment]
Do you just want a `--force` flag to overwrite everything, or something more subtle?

**Comment by ashleygwilliams** [comment]
i definitely think if there was a force option and the error suggested it that would improve the situation. i suspect something more subtle is possible and preferable but i haven't come up with anything yet :)

**Comment by Gankra** [comment]
this was fixed by making `cargo dist init` interactive and rerunnable as an updater

* #227 
* #230
