### ISSUE TITLE
prompt to update your cargo-dist-version if regenerate-ci detects a version mismatch

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/cargo-dist#166]
this is likely not terribly impactful beyond folks who are building on top of dist, but i went to update to prerelease12 for oranda and realized i wasn't sure if i should update the schema as well. my suspicion based on how things work from a purely funcitonally perspective is no- but i also know that some folks versioning lib/tool pairs like this in lock step even if no updates are made to keep compat obvi. wasn't sure what your thinking was on this and figured it may be useful to add this as a small doc deep in the book (since it's not super applicable to most users) once we figure out what we want it to be.

**Comment by ashleygwilliams** [comment]
oh actually, i misread the error because i was thinking about this issue and it has to do with my cargo-dist version and not my cargo-dist-schema version. 

i want self-update haha

**Comment by Gankra** [comment]
Gonna retool this into an issue for us to, instead of an error on version mismatches, say 

"do you want to update cargo-dist-version from 0.0.3 to 0.0.4? [Y/n]"

And then edit their Cargo.toml

**Comment by Gankra** [comment]
This will be fixed in 0.0.6 by having `cargo dist init`'s new interactive mode do this, to make it function like an updater

* #227 
* #230
