### ISSUE TITLE
Allow user to pick packaging scheme

### ISSUE THREAD

**Issue by Gankra** [axodotdev/cargo-dist#17]
Currently we just use `.zip` when targetting windows and `.tar.xz` everywhere else, but we should allow the user to configure this in the settings.

https://github.com/taiki-e/upload-rust-binary-action has some examples for inspiration.

**Comment by Gankra** [comment]
Note that this information will need to be threaded through to installers and generate-ci. Currently those things slightly hardcode zip/tar extensions. Unclear if installers should get these choices baked in, or if they should be written to investigate the github release's contents and more intelligently detect what to do (this may be necessary if we want installer scripts to meaningfully support version-to-install-as-an-argument-to-the-script.

**Comment by Gankra** [comment]
Now that #115 is implemented we're better postured to do this, some notes on Things You'll Need To Do:

* Config: 
  * Add field(s) to the [DistMetadata config](https://github.com/axodotdev/cargo-dist/blob/main/cargo-dist/src/tasks.rs#L106) (this adds it to Cargo.tomls)
  * Merge field(s) in [merge_workspace_config](https://github.com/axodotdev/cargo-dist/blob/7c77b2908359a03000717df5b767d26e44b99602/cargo-dist/src/tasks.rs#L211) so packages can override
  * ~~Add an equivalent CLI flag and merge it too~~ probably not appropriate here!
  * Read field(s) in [make_executable_zip_for_variant](https://github.com/axodotdev/cargo-dist/blob/7c77b2908359a03000717df5b767d26e44b99602/cargo-dist/src/tasks.rs#L966-L974)

* Build:
  * In priniciple the actual build steps already support all the formats, nothing to do! (test this...)

* Teach the installers to handle these formats
  * Clear the assertions [(1)](https://github.com/axodotdev/cargo-dist/blob/main/cargo-dist/src/installer.rs#L54) [(2)](https://github.com/axodotdev/cargo-dist/blob/main/cargo-dist/src/installer.rs#L136) from installer.rs that complain you haven't implemented the feature
  * Teach installer.sh to handle the new format (maybe only needs zip support?)
    * [Handle the value of _zip_ext here](https://github.com/axodotdev/cargo-dist/blob/7c77b2908359a03000717df5b767d26e44b99602/cargo-dist/src/installer.sh#L74)
  * The installer.ps1 to handle the new format (presumably it will choke on any tar.whatever?)
    * [Handle the value of zip_ext here](https://github.com/axodotdev/cargo-dist/blob/7c77b2908359a03000717df5b767d26e44b99602/cargo-dist/src/installer.ps1#L61-L64)
    
In principle I like the idea of windows-zip-style and unix-zip-style being individually configurable, but we could also opt for a unified setting with "you didn't set it" default to "platform specific behaviour".

#125 also suggested a "no zip" setting, which I'm a bit disinclined towards because then you need to rename the binary when you download it (for similar reasons I'm thinking about making `.pdb` artifacts always zipped too, those have Especially Significant names due to #116).

**Comment by AustinWise** [comment]
Windows 10 1803 and later [should have tar installed](https://learn.microsoft.com/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows), so potentially the installer could use that to handle `.tar.gz` files.

**Comment by Gankra** [comment]
This is fixed in 0.0.6 with the introduction if "windows-archive" and "unix-archive" keys

* #211 
* https://opensource.axo.dev/cargo-dist/book/config.html#windows-archive (will be live when 0.0.6 is released ~today)
