### ISSUE TITLE
Error output from invalid compilation target

### ISSUE THREAD

**Issue by sondrelg** [axodotdev/cargo-dist#177]
Hi :slightly_smiling_face: 

Thanks for creating this project, it looks neat!

I've just spent a few hours trying to get the init workflows running, and I eventually discovered that the problems I was having were due to me trying to cross-compile to macos arm64, and that's not supported until 0.0.4 (https://github.com/axodotdev/cargo-dist/pull/172). My problem therefore seems solved, I'll test the pre-release for that version :partying_face: 

Just wanted to quickly raise this: do you think this error could be improved?

```
Run # Actually do builds and make zips and whatnot
analyzing workspace:
  bar (publish = false)
    [bin] bar
  foo
    [bin] foo

bundling foo-v0.1.9-aarch64-apple-darwin.tar.xz
building cargo target (aarch64-apple-darwin/dist)
   Compiling bar v0.1.0 (/home/runner/work/dist-demo/dist-demo/apps/bar)
   Compiling foo v0.1.9 (/home/runner/work/dist-demo/dist-demo/apps/foo)
error: could not compile `foo` due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `bar` due to 4 previous errors

  × failed to find bin foo (foo 0.1.9 (path+file:///home/runner/work/dist-
  │ demo/dist-demo/apps/foo))
```

This is the error output when trying to target the invalid arch. Maybe being more explicit here could save others time in the future, assuming some type of target validation is trivial to implement?

**Comment by alexkirsz** [comment]
I'm seeing something similar, but I believe my issue is due to another problem when compiling for a particular target. However, it looks like the command swallows all error messages, so it only ends up showing `error: could not compile `x` due to N previous errors`.

https://github.com/alexkirsz/dispatch/actions/runs/4901475080/jobs/8752781885

**Comment by IgnisDa** [comment]
I have the same problem.

**Comment by coastalwhite** [comment]
If it may help people, I also ran into some problems, and it didn't realize cargo dist was running using Rust 1.67.1 instead of a newer version. I updated the Cargo.toml `rust-toolchain-version` and the `rustup update ...` in the `.github/workflows/release.yml` to the desired version.

**Comment by Gankra** [comment]
A bunch of this is improved in 0.1.0/0.2.0:

* (0.1.0) We deprecated rust-toolchain-version (use [rust-toolchain.toml](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) if you want pinning)
* (0.2.0) We now forward more compiler messages to you so you should be able to see things go wrong.
