### ISSUE TITLE
add oranda hide to installer portion of generated release body

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/cargo-dist#199]
for folks not using oranda this will have no visible effect unless they inspect the generated markdown, for folks using oranda this will remove unecessarily repeated information

**Comment by Gankra** [comment]
We discussed this and this is redundant with [announcement_changelog](https://github.com/axodotdev/cargo-dist/blob/6c0c5c43922a95b990433c0949a86512e299727b/cargo-dist-schema/cargo-dist-json-schema.json#L7-L13) in the schema which already is "just" the changelog without the gunk we add to the github release (which is announcement_github_body).

**Comment by ashleygwilliams** [comment]
@SaraVieira ^
