### ISSUE TITLE
Copyright and license notice on the generated CI config

### ISSUE THREAD

**Issue by rpavlik** [axodotdev/cargo-dist#204]
My projects follow <https://reuse.software> so I ensure that there is copyright and license info for each file in my repo. As far as I can tell, the generated CI file is just a part of this crate so it's probably "MIT or Apache-2.0". However, it's not clear what the copyright statement should be.

It would be great if this package was REUSE compliant, but I'd be happy with just a correct notice on the generated CI script.

**Comment by ashleygwilliams** [comment]
@rpavlik the generated CI files are indeed licensed the same as the project (MIT or Apache 2.0). i'm not familiar with the reuse software structure. what type of notice does it require? 

i'm not familiar with any frameworks putting license files on generated files (i've written a few but this is a new request for me), are there ecosystems that this is prevalent in?

**Comment by rpavlik** [comment]
I like knowing exactly under what terms I can use a file, so if a project is putting a file in my project, I want to make sure I can actually use it, etc. I think this is something the community has been a bit slow to do but e.g. it really helps folks like distribution packagers (as well as lawyers) when there's clear indication of copyright and license in each file. As a debian packager, the hardest part of the process is making an accurate copyright-notice file...

Sorry I forgot to include an example! It would look something like this:

```
Copyright 2022-2023, axodotdev
SPDX-License-Identifier: MIT or Apache-2.0
```

with the date and copyright holder adjusted as needed.

**Comment by ashleygwilliams** [comment]
appreciate the example @rpavlik ! i can see the value, and i wouldn't be opposed to adding this to the generated yaml- i am curious what @Gankra's thoughts are.

**Comment by Gankra** [comment]
This seems reasonable to add to our templates (although I don't think we can add it to the json files we generate for npm, since strict json... [although maybe we can use this](https://groups.google.com/g/nodejs/c/NmL7jdeuw0M/m/yTqI05DRQrIJ)). If @ashleygwilliams can decide on the ideal string to include, I can add it to all the templates.
