### ISSUE TITLE
default to the version specified in `rust-toolchain.toml` when `rust-toolchain-version` not provided

### ISSUE THREAD

**Issue by rukai** [axodotdev/cargo-dist#205]
I use cargo's `rust-toolchain.toml` to pin my rust version to a specific stable release.
This enforces that developers and CI all run the same version of rust.
It also allows me to set CI to fail if any rustc or clippy warnings occur without violating the "not rocket science" rule.

I think this should be the standard way to set what rust version to use, with the `rust-toolchain-version` acting as override and automatically setup when the user hasnt created a `rust-toolchain.toml`

I think the following logic would work:
* If a `rust-toolchain.toml` specifies a `channel` (the toolchain version) then:
   * `cargo dist init` should not set a `rust-toolchain-version`
* If a `rust-toolchain.toml` specifies a `channel` (the toolchain version) and cargo dist's `rust-toolchain-version` is unset then:
   * `cargo dist generate-ci` should not include the `name: Install cargo-dist` section. The `rust-toolchain.toml` will cause rustup to automatically install the specified toolchain the first time `cargo` is invoked in a directory containing `rust-toolchain.toml` or one of its subdirectories)

**Comment by ashleygwilliams** [comment]
i think this is an interesting idea, @rukai - thanks for submitting! given that the project has a goal to fit well into rust workflows, respecting rustup configs makes sense to me. 

when you get a sec, i'm curious what your thoughts are @Gankra?

**Comment by Gankra** [comment]
This is now at the top of my queue, rust-toolchain.toml is clearly just a better/official version of what i hacked up, and i should probably deprecate my config in favour of this.
