### ISSUE TITLE
GitHub release workflow contains Useless Uses of Cat

### ISSUE THREAD

**Issue by jwodder** [axodotdev/cargo-dist#212]
The `release.yml` workflow created by `cargo dist init --ci=github` contains multiple invocations of the form "`cat dist-manifest.json | jq ...`".  The `cat` and pipe here are unnecessary, as `jq` is perfectly capable of taking the name of a file to read as an argument.  Thus, for example, the line:

    ANNOUNCEMENT_TITLE=$(cat dist-manifest.json | jq --raw-output ".announcement_title")

can be rewritten as:

    ANNOUNCEMENT_TITLE=$(jq --raw-output ".announcement_title" dist-manifest.json)

**Comment by Gankra** [comment]
Totally fair, I intentionally wrote the scripts to be extremely simplistic / mindless, and welcome these kinds of cleanups by folks who are better at it than me.
