### ISSUE TITLE
Use bash on all GitHub Actions systems to simplify code

### ISSUE THREAD

**Issue by jwodder** [axodotdev/cargo-dist#214]
The "Run cargo-dist" step in the autogenerated GitHub release workflow contains the comment:

https://github.com/axodotdev/cargo-dist/blob/f42119afb5a50f0c7cd203f50bba28433056a2cd/cargo-dist/src/ci.yml#L99-L102

I am here to inform you that you can use bash on all three platforms by adding the field "`shell: bash`" to the step; [see the GitHub docs for more information](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell).  You can even make every step throughout the workflow use bash by putting the following at the top level of the YAML document:

```
defaults:
  run:
    shell: bash
```

**Comment by Gankra** [comment]
So I am aware of this, but the mental calculus was as follows:

* "bash on windows" sketches me out, and I honestly trust "a polyglot of the shared subset of features" more (given the minor level of weirdness it introduces)
* the polyglot entertains me and brings light in the miserable darkness of iterating on CI scripts

That said if you have a strong argument to tip the scales, I'm all ears.

**Comment by panekj** [comment]
IMO, I would be for using PowerShell (`pwsh`) instead of Bash since it's available on all platforms while not being as deranged as Bash.
