### ISSUE TITLE
Support generating GitHub Actions workflows that upload dist artifacts as workflow artifacts

### ISSUE THREAD

**Issue by jwodder** [axodotdev/cargo-dist#217]
[My pre-`cargo-dist` build-and-release setup](https://github.com/jwodder/confab/blob/c1d4d3884486224120656a6ede16036b8af9da99/.github/workflows/build.yml) includes a feature that I suspect others may find useful: whenever a commit is pushed to the default branch or a PR opened/updated (i.e., not just when a version tag is pushed), the workflow builds my App for various targets and uploads the executables as [workflow artifacts](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts) so that I can download them from GitHub and test them on other systems without having to install Rust and without having to make a release for CI-built assets.  This workflow is even part of the release process, as, if the run was triggered by a version tag, the workflow goes on to package the executables in zips and upload them as release assets (without having a separate workflow that would duplicate compilation).

Do you think this is something you might add to `cargo-dist`'s autogenerated workflows?

**Comment by Gankra** [comment]
This is definitely worth considering, and might enable things that want #45

**Comment by ashleygwilliams** [comment]
@jwodder this was implemented (a while ago!) as a feature called "pr-run-mode = upload" https://opensource.axo.dev/cargo-dist/book/reference/config.html#pr-run-mode

does this meet your needs or do you have any feedback on it? i am going to close but if the current feature doesn't meet you needs, please reopen or file a new issue!
