### ISSUE TITLE
msi (un)installer support

### ISSUE THREAD

**Issue by Gankra** [axodotdev/cargo-dist#23]
This would be another potential killer app, but should be out of scope for the MVP.

**Comment by CAD97** [comment]
[cargo-wix](https://github.com/volks73/cargo-wix) uses [the WiX toolset](https://wixtoolset.org/) to generate MSI installers.

Most of its functionality is available through the [library crate](https://docs.rs/cargo-wix/latest/wix/index.html) and could be reused by cargo-dist. (Though obviously this will require installing the WiX toolset on CI and having cargo-wix initialized.)

**Comment by Gankra** [comment]
![image](https://user-images.githubusercontent.com/1136864/216279354-83092783-5139-47e1-b469-3c8128121396.png)

uninstall button also works :)

**Comment by Gankra** [comment]
Some upstream cargo-wix work: https://github.com/volks73/cargo-wix/pull/198

**Comment by Gankra** [comment]
UX is pretty miserable once you put it on the internet and download it (WITHOUT signing) -- windows throws up 3 barriers to getting to the actual installer:

![image](https://github.com/axodotdev/cargo-dist/assets/1136864/e51be54b-6ef8-499b-aba4-b9a0e0405039)
![image](https://github.com/axodotdev/cargo-dist/assets/1136864/4f9f0e24-f664-45a2-9f10-243a55caaa96)
![image](https://github.com/axodotdev/cargo-dist/assets/1136864/c1ac2dbd-866b-4ead-986d-163e3421496a)
![image](https://github.com/axodotdev/cargo-dist/assets/1136864/dd6f3b67-bda9-4e93-96a2-7dbc6c0cc638)

So while I might land signing-less support for this initially, working out the story for signing will be pretty important for making this Good (cargo-wix can dispatch to windows signtool, but still need to tell users how the heck to setup signtool certs).

**Comment by Gankra** [comment]
cargo-dist v0.3.0-prerelease.5 has an I think shippable mvp, I just need to write the docs.

**Comment by Gankra** [comment]
Closing in favour of #432 just so I don't forget what's left
