### ISSUE TITLE
Include checksums in releases for file integrity

### ISSUE THREAD

**Issue by SkeletalDemise** [axodotdev/cargo-dist#240]
I noticed that cargo-dist doesn't include hashes in the generated GitHub release or the `dist-manifest.json` file.
It would be a good idea to include SHA-256 hashes of the uploaded artifacts in the release for file integrity.

The workflow I'm using is from `cargo dist init --ci=github`
If there's an easy way to modify it to generate hashes, let me know.

**Comment by Gankra** [comment]
Gonna close this as a dupe of https://github.com/axodotdev/cargo-dist/issues/119

It is not yet supported, but it's planned for the next few weeks.

**Comment by SkeletalDemise** [comment]
Thanks, I searched but didn't find that issue.
