### ISSUE TITLE
Installer and download links don't work when repository is specified with .git

### ISSUE THREAD

**Issue by DCNick3** [axodotdev/cargo-dist#263]
On github, the canonical clone url for repository ends with `.git` (`https://github.com/user/repo.git`), while the canonical url for the web interface doesn't have `.git` (`https://github.com/user/repo`).

However, you still can clone repo with url without the `.git` and go to the web interface by url that has git.

This creases some confusion between those two, and with cargo book saying that "The repository field should be a URL to the source repository for your package.", it's not clear which url should be used. There are about 5.5k crates on crates.io that specify the repository url with `.git` and around 88k without.

However, you can't use `.git` url to create release urls, so specifying such a url makes `cargo-dist` create invalid urls in the downloads table and in the installers.

**Comment by Gankra** [comment]
We should absolutely do this
