### ISSUE TITLE
how can I tell cargo dist to only publish to my github repo?

### ISSUE THREAD

**Issue by Masber** [axodotdev/cargo-dist#265]
Hi, 
At the moment, when I run cargo dist patch --execute, the githab workflow fails because publish = false in cargo.toml . I don't want to publish my artifact into crates.io but only in github.com

How can I do this?

thank you

**Comment by Gankra** [comment]
You should be able to do this by adding [dist = true](https://opensource.axo.dev/cargo-dist/book/config.html#dist) to your `[workspace.metadata.dist]` section of your Cargo.toml.

You can verify this worked locally by running `cargo dist plan`
