### ISSUE TITLE
 dist-manifest.json has wrong download link

### ISSUE THREAD

**Issue by Masber** [axodotdev/cargo-dist#267]
Hi,

I got cargo dist and cargo release installed and it can create releases and push artifacts to my GitHub repository, however, I am getting a 404 error (page not found) under the release section when I click the download link, the link is as below which looks suspicious. I don't understand why the README.md file is in the middle of the URL and I don't eve have a releases folder in my GitHub repo.

https://github.com/eth-cscs/manta/blob/main/README.md/releases/download/v0.6.9/manta-x86_64-unknown-linux-gnu.tar.xz

Any idea?

**Comment by ashleygwilliams** [comment]
oh hrm, this does look quite strange. i just took a look at the repo and the latest release had this link (https://github.com/eth-cscs/manta/releases/download/v0.6.11/manta-x86_64-unknown-linux-gnu.tar.xz) which looks correct- did you figure out the issue? if not- could you share more about your project setup that made the release with this link in it so i can take a look?

**Comment by Masber** [comment]
@ashleygwilliams yeah at the end I could figure out what wash the issue and got it fixed by the time you checked.
@DCNick3 thanks for pointing out the issue :)
