### ISSUE TITLE
Support for Linux Arm

### ISSUE THREAD

**Issue by gregorni** [axodotdev/cargo-dist#324]
It would be cool to have support for Linux on Arm64/Aarch64 devices with the `aarch64-unknown-linux-gnu` target, along with the current x86_64 support.

This would allow building for the Raspberry Pi, Asahi Linux systems, Aarch64 Flatpaks, Pine64 devices, and so on.

**Comment by zahash** [comment]
Yes, please. I also have a raspberry pi and right now cargo-dist doesn't build for aarch64-unknown-linux-gnu

**Comment by mistydemeo** [comment]
This will be supported with the upcoming 0.6.0 release. We're planning to begin distributing aarch64-unknown-linux-gnu and aarch64-unknown-linux-musl binaries.

**Comment by DCNick3** [comment]
Do I understand it right, that I would have to provide a linux aarch64 runner myself to be able to use it, since github still doesn't provide hosted arm linux runners and cargo-dist doesn't do cross-compilation yet?

**Comment by mistydemeo** [comment]
Yes, that's right. For our own binaries, we're using BuildJet's runners. GitHub have a closed beta of paid ARM Linux runners as well: https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/

Now that we have custom runner support, I'm going to close this issue. Feel free to open issues if you have further questions though!
