### ISSUE TITLE
passing arguments to cargo: -Z bindeps

### ISSUE THREAD

**Issue by webern** [axodotdev/cargo-dist#347]
I need to build with something like this:

`cargo +nightly build -Z bindeps`

Or

`RUSTC_BOOTSTRAP=1 cargo build -Z bindeps`

Can we pass these arguments to cargo? e.g.

`RUSTC_BOOTSTRAP=1 cargo dist build --tag=${{ github.ref_name }} --output-format=json ${{ matrix.dist-args }} -- -Z bindeps`

Admittedly I haven't tried it, but I'm looking at `cargo dist build --help` and the GitHub issues and not seeing the answer to this.

I have a `.cargo/config.toml` that loos like this, but for reasons I don't understand, it doesn't seem to cause `cargo build` to work as if it were invoked with `RUSTC_BOOTSTRAP=1 cargo build -Z bindeps`:

```toml
[unstable]
bindeps = true

[env]
RUSTC_BOOTSTRAP = "1"
```

The problem manifests like this:

```
Run cargo dist plan --tag=origin-v0.0.3-deleteme1 --output-format=json > dist-manifest.json
analyzing workspace:
  × your cargo workspace has an issue
  ├─▶ `cargo metadata` execution failed
  ╰─▶ `cargo metadata` exited with an error: error: failed to load manifest
      for workspace member `/home/runner/work/twoliter/twoliter/twoliter`
      
      Caused by:
        failed to parse manifest at `/home/runner/work/twoliter/twoliter/
      twoliter/Cargo.toml`
      
      Caused by:
        `artifact = …` requires `-Z bindeps` (buildsys)
```

**Comment by Gankra** [comment]
I agree we should have a good story for this. I'm not sure if existing things like [.cargo/config.toml](https://doc.rust-lang.org/cargo/reference/config.html) are usable for your usecase. ([example of cargo-wix suggesting it](https://volks73.github.io/cargo-wix/cargo_wix/index.html#c-runtime)).

**Comment by Gankra** [comment]
Have you tried adding this rust-toolchain.toml to your repo?

```
[toolchain]
channel = "nightly-2023-08-29"
profile = "minimal"
```

After some local experimentation it appears that the error you get is symptomatic of the fact that *stable* rust toolchains completely ignore `[unstable]`, producing this cryptic error. cargo-dist defaults to using the the rust toolchain installed in github CI, which is a recent stable one.

By adding a rust-toolchain.toml, you tell rustup to force switch to the given nightly when 'cargo' or 'rustc' is invoked in your project.

**Comment by webern** [comment]
> Have you tried adding this rust-toolchain.toml to your repo?

Thank you. I don't quite understand that since rustup isn't involved in the invocation of, e.g. `cargo build`.

In any event, I figured this out by changing to nightly in the actions workflow. Thank you.

**Comment by Gankra** [comment]
@webern surprisingly, rustup *is* involved in `cargo build`!

https://rust-lang.github.io/rustup/concepts/index.html#how-rustup-works

> rustup is a toolchain multiplexer. It installs and manages many Rust toolchains and presents them all through a single set of tools installed to ~/.cargo/bin. The [rustc](https://doc.rust-lang.org/rustc/) and [cargo](https://doc.rust-lang.org/cargo/) executables installed in ~/.cargo/bin are [proxies](https://rust-lang.github.io/rustup/concepts/proxies.html) that delegate to the real toolchain. rustup then provides mechanisms to easily change the active toolchain by reconfiguring the behavior of the proxies.
