### ISSUE TITLE
Additional non-Rust artifacts in the same Github release

### ISSUE THREAD

**Issue by neocturne** [axodotdev/cargo-dist#349]
Is there a way to insert additional workflow steps between Github release creation and marking it as non-draft, besides editing this into `release.yml` each time I regenerate it? This would be useful to upload additional (e.g. non-Rust) artifacts to the same release.

I believe that for my purposes the ability to copy additional jobs from a template into `release.yml` and making the final `publish-release` depend on their success would be sufficient. Does something like this already exist, or does it sound like a worthwhile addition?

**Comment by Gankra** [comment]
The plan is for this to be handled by #379, which is what we're working towards for the next couple weeks.
