### ISSUE TITLE
reintroduce column headers, add human-readable platform column 

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/cargo-dist#356]
in 0.1.0 the download artifacts table lost it's headers due them being identified, reasonably, as redundant. however github markdown doesn't allow tables w/o headers so the outcome is that the table looks "broken":
<img width="540" alt="Screenshot 2023-08-23 at 4 53 32 PM" src="https://github.com/axodotdev/cargo-dist/assets/1163554/fa1eb8d5-d77e-46e3-9095-ee15ddc7e4e6">

i propose:
1. adding a new "platform" column that gives a "human readable" version of the target triple
2. re-add the headers, given the additional utility they provide for said platform column

added benefit: it's symmetrical with how we handle this in oranda:
<img width="842" alt="Screenshot 2023-08-23 at 4 53 42 PM" src="https://github.com/axodotdev/cargo-dist/assets/1163554/ef5de98e-0d3e-4517-9a89-ce05564b250d">

**Comment by mistydemeo** [comment]
Quick stab at it: https://github.com/axodotdev/cargo-dist/pull/357

**Comment by ashleygwilliams** [comment]
@mistydemeo the "human readable platform" mapping is in oranda- i wonder if we should shift that to axoproject so that cargo-dist could share it? https://github.com/axodotdev/oranda/blob/cd599998c40aa21924372835dc410cb44f836bdd/src/data/artifacts/inference.rs#L330

**Comment by mistydemeo** [comment]
That sounds like a good place for it.
