### ISSUE TITLE
Add support for publishing releases on all tags (do not enforce `v` prefix)

### ISSUE THREAD

**Issue by matusf** [axodotdev/cargo-dist#369]
As for now, the actions only run on tags that satisfies following regex `*-?v[0-9]+*`. I'd like to create tags without the leading `v` as it does not follow the semantic versioning[^0]. Could you please consider adding support for it?

[^0]: https://semver.org/#is-v123-a-semantic-version

**Comment by Gankra** [comment]
This is already in flight with #346 

🐱

**Comment by Gankra** [comment]
This is in 0.2.0-prerelease.6 ([docs](https://opensource.axo.dev/cargo-dist/book/workspace-guide.html#announcement-tags)), and 0.2.0 should be out by end of week.
