### ISSUE TITLE
typo "this is mode is"

### ISSUE THREAD

**Issue by tshepang** [axodotdev/cargo-dist#372]
https://github.com/axodotdev/cargo-dist/blob/b3c413953f319841c755dc9247035122f26918f3/cargo-dist/templates/ci/github_ci.yml.j2#L33

Found it above and in a few other places, so not doin PR in case there is tooling that populates things:
```
❯ rg 'this is mode'
cargo-dist/templates/ci/github_ci.yml.j2
33:# (cargo-dist-able) packages in the workspace with that version (this is mode is

cargo-dist/tests/snapshots/akaikatana_repo_with_dot_git.snap
1274:# (cargo-dist-able) packages in the workspace with that version (this is mode is

cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap
2147:# (cargo-dist-able) packages in the workspace with that version (this is mode is

cargo-dist/tests/snapshots/axolotlsay_basic.snap
2147:# (cargo-dist-able) packages in the workspace with that version (this is mode is

cargo-dist/tests/snapshots/akaikatana_basic.snap
1274:# (cargo-dist-able) packages in the workspace with that version (this is mode is

**Comment by Gankra** [comment]
The only real typo is in `cargo-dist/templates/ci/github_ci.yml.j2`, all the others are snapshot-tests of the output of applying that template.

**Comment by tshepang** [comment]
oh, kool... I see I would have needed to run `cargo insta` (the tooling I suspected existed) after modifying the j2 file
