### ISSUE TITLE
release lifecycle plugins

### ISSUE THREAD

**Issue by Gankra** [axodotdev/cargo-dist#379]
This is the followup and ultimate payoff of #378 

Expose/upgrade `publish-jobs = [...]` and `upload-jobs = [...]` so that users can refer to their own .yml files that cargo-dist embeds into release.yml and weaves into the dependency graph. This could be used for:

* Adding custom publish steps ("[publish to this other package manager](https://github.com/axodotdev/cargo-dist/blob/e01b5e390e3f10cc6ff1812066b64c96e3a8e3ca/.github/workflows/publish-release.yml)", "post to social media", ...)
* Adding ("[generate a schema file](https://github.com/axodotdev/cargo-dist/blob/e01b5e390e3f10cc6ff1812066b64c96e3a8e3ca/.github/workflows/append-release.yml)", "build this other installer", ...)
* Post-processing artifacts ("sign my binaries", "test the binaries", ...)

**Comment by mistydemeo** [comment]
Thinking about this a little more: I'm not sure we want the extra jobs to be YML we include in `release.yml`, because then we tie ourselves too specifically to GitHub. We've got plans to support other CI systems - I wouldn't want us to have ended up limiting ourselves there.

**Comment by Gankra** [comment]
I figured the feature would be ci-backend-generic by us taking generic names like `publish-jobs = ["my-package-manager"]` and us taking that to mean "in the github ci backend, we expect to find `.github/workflows/publish-my-package-manager.yml`". Presumably this approach could be generalized to other systems..?

(And one would assume that enabling multiple CI backends at once would be exceedingly rare)

**Comment by mistydemeo** [comment]
> I figured the feature would be ci-backend-generic by us taking generic names like publish-jobs = ["my-package-manager"] and us taking that to mean "in the github ci backend, we expect to find .github/workflows/publish-my-package-manager.yml". Presumably this approach could be generalized to other systems..?

I find myself wondering if we should make it more generic than that? Have the user define a name and a script, and we then define a job that runs that script. So we can guarantee some environment variables, but otherwise they're not touching CI-specific stuff.

Am I overthinking things? Maybe. I guess I'm just wondering if we really want the user to be writing CI system-specific files or not. Otherwise, if the user's got workflows in `.github/workflows/blah`, those are already getting triggered automatically by Actions, right? They don't need us to do that for them.

> (And one would assume that enabling multiple CI backends at once would be exceedingly rare)

I've seen it happen, but it's definitely more of a "big company with weird compliance stuff" situation.

**Comment by Gankra** [comment]
keeping a paper trail for later, much discussion happening in this axo.dev internal design doc: https://www.notion.so/axodotdev/cargo-dist-Lifecycle-Hooks-6c9d4218a70b44afb72621c8fc454b71

current plan is something that looks a lot like git's pre-/post- hooks with 5 stages to hook:

* "plan" (`cargo dist plan`, determine stable URLs for uploads)
* "build" (`cargo dist build`)
* "host" (upload artifacts to a stable URLs)
* "publish" (`cargo publish`, `npm publish`, ...)
* "announce" (socials, github release, etc)

"host" is a concept that github muddies because draft github releases have unstable URLs, making them unusable as hosting. This forces you to "race" between the Github Release announcing itself and npm packages being able to actually fetch things. We don't want to restrict ourselves to this muddy design, so we want to have it split out (and potentially let the user pick their poison on github).

**Comment by Gankra** [comment]
We have a minimal version of this.
