### ISSUE TITLE
Homebrew taps update with prerelease versions

### ISSUE THREAD

**Issue by mistydemeo** [axodotdev/cargo-dist#398]
Currently, we push every tagged release to a Homebrew tap. For example: https://github.com/axodotdev/homebrew-tap/commit/8f5ef81fc87944d7c1eb83b037b3d40e71646450

While this is consistent with how we always push to releases, we're able to mark an entire GitHub release as a prerelease in a way we don't do to the Homebrew formula. We should likely either stop pushing prereleases to the tap, or add a configuration flag as to whether to push prereleases to package managers.

**Comment by Gankra** [comment]
Does homebrew have a way to let a prerelease channel coexist with a release channel? (Worth noting this is also an issue for crates.io and npm, once we add builtin publish-jobs for those too (crates.io's download metrics get wonky with prereleases, and npm requires you to pass a special flag to specify a release is a prerelease, both of these are things we're annoyed with with oranda's hacked together publish jobs.)

**Comment by mistydemeo** [comment]
> Does homebrew have a way to let a prerelease channel coexist with a release channel?

Unfortunately, no. It once did, but it was removed as Homebrew removed more from-source oriented installation methods.

> (Worth noting this is also an issue for crates.io and npm, once we add builtin publish-jobs for those too (crates.io's download metrics get wonky with prereleases, and npm requires you to pass a special flag to specify a release is a prerelease, both of these are things we're annoyed with with oranda's hacked together publish jobs.)

IMO in that case we should consider a general "publish prerelease artifacts to package managers" flag in the manifest.
