### ISSUE TITLE
cargo dist manifest: Out of date contents

### ISSUE THREAD

**Issue by sondrelg** [axodotdev/cargo-dist#400]
Testing the new v0.3.0-prelease.1, I'm no longer able to generate a manifest, using `cargo dist manifest`. 

Instead, I get this error:
```json
{
  "diagnostic": {
    "message": "/home/user/repos/project/.github/workflows/release.yml:1 has out of date contents and needs to be regenerated:\n-\n+# Copyright 2022-2023, axodotdev",
    "severity": "error",
    "causes": [],
    "help": "run 'cargo dist init' or 'cargo dist generate' to update the file",
    "labels": [],
    "related": []
  }
}
```

It seems like the CLI now is very strict about how the release workflow should look, which is a little impractical. I've written my own release workflow, with different caching, different triggers, and with everything I don't need, stripped away. This new requirement is therefore a little obstructive.

Is this intentional, or would you consider this a bug?

## How to replicate

- Upgrade to the newest release, 
- Generate a release workflow file with `cargo dist generate`,
- Change more or less any attribute, 
- Run `cargo dist manifest`

**Comment by mistydemeo** [comment]
We've added a new configuration value, `allow-dirty`, to accommodate that usecase. You can either add it to your `Cargo.toml` (`allow-dirty = ["ci"]`), or pass `--allow-dirty` at the commandline when calling `cargo dist`. Does that work for you?

**Comment by sondrelg** [comment]
Yes, that works :clap: Thanks @mistydemeo :bow:

**Comment by mistydemeo** [comment]
Great! Let us know if you have any other problems.
