### ISSUE TITLE
better installer behaviour

### ISSUE THREAD

**Issue by Gankra** [axodotdev/cargo-dist#41]
Various improvements:

* cargo home
  * [x] respect CARGO_HOME
  * [ ] Update `~/.cargo/.crates.toml` to register the binary?
* other install dirs
  * [x] #235 
  * [ ] Look for other big likely-on-PATH dirs?
* better installs
  * [ ] #314 
  * [ ] Run an "install" subcommand of the binary itself?

**Comment by Gankra** [comment]
Discussing this with Ashley we concluded that it might be for the best if we do like [apollo's rover does](https://github.com/apollographql/rover/tree/main/installers/binstall) and try to build out machinery for CLIs to have an `install` subcommand (which would also theoretically support self-update and uninstalling and whatnot).

That way we can have more hairy logic in rust and not bash scripts (yuck!). This may involve us building out a reusable library for everyone to use for this. It's possible this library already exists in some of the [binstalk crates in cargo-binstall](https://github.com/cargo-bins/cargo-binstall/tree/main/crates), or is aching to be extracted from them.

**Comment by Gankra** [comment]
Relevant issues rustup had a while back 

* https://github.com/rust-lang/rustup/pull/2387
* https://github.com/rust-lang/rustup/issues/2106

**Comment by jyn514** [comment]
It would be nice if this also respected CARGO_HOME instead of hardcoding ~/.cargo.

**Comment by mistydemeo** [comment]
We should update the milestone again.

**Comment by Gankra** [comment]
This issue doesn't really make much sense anymore / needs to be revived as several smaller issues.
