### ISSUE TITLE
better templating for generating installers/ci

### ISSUE THREAD

**Issue by Gankra** [axodotdev/cargo-dist#42]
Currently I just have a bunch of HUGE string literals that start/end between spots where I need to inject values and... that sucks lol. We should be using some proper rust string templating library. I just hacked it up like this to get an MVP working.

**Comment by Gankra** [comment]
cc @ashleygwilliams I bet you have opinions on this

**Comment by ashleygwilliams** [comment]
i both do and don't - templating is tough. it's good but there's no *great* tool. thankfully this is internal and so we don't get stuck with someone else's public interface. i've used liquid for cargo-generate and that seemed fine (@killercup picked it iirc) but the former rubyist in me always like handlebars. i'd say go with your gut - i suspect everyone comes to hate the limitations of their templating engine, no matter which they pick.

**Comment by ashleygwilliams** [comment]
i also think it is potentially ok to just keep concatenating strings. [wasm-bindgen *still* does that *to write JS*](https://github.com/rustwasm/wasm-bindgen/blob/main/crates/cli-support/src/js/mod.rs#L145) and it is *fine*, we'll just want tests ;)

**Comment by Gankra** [comment]
The cool thing about everyone agreeing to use `{}` for templating is that you need to write stuff like `{{{{blah}}}}` whenever you want to template a templated thing 😭
