### ISSUE TITLE
don't mention generate in error messages

### ISSUE THREAD

**Issue by Gankra** [axodotdev/cargo-dist#435]
iirc one does, but we should pretend init is the only way to run generate

**Comment by ashleygwilliams** [comment]
@Gankra q on this: init is the interactive configuration thing, assuming i dont want to change my config and want things to generate just from what i have- does generate do this? will it error if i have config incompatible with the current version?

mostly: after not originally seeing it- i see the value of not having to go through the interactive

**Comment by Gankra** [comment]
`generate` is responsible for most integrity checks, but `init` has some more advanced logic on top of it that can help you repair or add missing information, and also handles updating cargo-dist, so I always want to funnel the user into it by default. Nothing prevents you from power-using `generate`.

**Comment by Gankra** [comment]
last vertiges of this done in #444
