### ISSUE TITLE
failed to find bin

### ISSUE THREAD

**Issue by IgnisDa** [axodotdev/cargo-dist#438]
I have been getting this error only on the windows Github runner:

https://github.com/IgnisDa/ryot/actions/runs/6236595310/job/16932011837#step:7:1174 (the "Run cargo-dist" step).

I am using cargo-dist version `0.2.0`.

**Comment by Gankra** [comment]
The actual error is from the windows linker / rustc a few lines above:

> LINK : fatal error LNK1181: cannot open input file 'Packet.lib'

Does that sound familiar to you? Are you normally able to build your application on windows, or is this the first time you're trying?

**Comment by IgnisDa** [comment]
It used to work until v0.0.7, then stopped working when I upgraded to v0.1.0. I posted on an existing similar issue here, and you replied that v0.2.0 might fix it. I upgraded to v0.2.0 yesterday.

No, I haven't built my app in windows.

**Comment by Gankra** [comment]
Ok so did some digging/testing, using the following:

```
mkdir apps/frontend/out
cargo build
```

* on linux this works as expected
* on windows i get `LINK : fatal error LNK1181: cannot open input file 'Packet.lib'` as you see in CI

So it indeed seems like your pure cargo build got broken on windows at some point, but I'm not sure why/how. Possibly one of your dependencies doesn't work on windows..? It doesn't seem specific to `cargo dist`, so I'm afraid I can't help much more than that at the moment. 


----

I also noticed you're doing a ton of hand-editing to this file, which is cool! We're planning a proper plugin system to make things easier to customize/extend while still letting cargo-dist manage this file for you (to avoid desyncs): https://github.com/axodotdev/cargo-dist/issues/379

**Comment by IgnisDa** [comment]
> It doesn't seem specific to cargo dist, so I'm afraid I can't help much more than that at the moment.

Do you have any pointers on what the problem could be?

> I also noticed you're doing a ton of hand-editing to this file, which is cool!

Which file are you talking about?

**Comment by Gankra** [comment]
> Do you have any pointers on what the problem could be?

It looks like you're running into an issue with `pnet` -- apparently it's a known issue and their README discusses it:

https://github.com/libpnet/libpnet#windows

> Which file are you talking about?

releases.yml -- the happy-path design has cargo-dist editing this actively whenever details of your build changes. If you update to the upcoming 0.3.0 you will need to set `allow-dirty = ["ci"]` or else it will be treated as an error to have the file be hand-edited like this.

To be clear, you're using cargo-dist perfectly fine, we're just working on making more of what you're doing "on the happy path" where we can do more of this stuff for you.

e.g. #365

**Comment by Gankra** [comment]
gonna close this as resolved on our end, hope this helps!

**Comment by IgnisDa** [comment]
Yeah I came across cargo-dist much later after the project started. I just integrated it into my project so that it can build executables, docker is the main method I distribute it.
