### ISSUE TITLE
homebrew formula generates empty `depends_on` clauses

### ISSUE THREAD

**Issue by msfjarvis** [axodotdev/cargo-dist#485]
Using cargo-dist v0.4.0-prerelease.1 on [this repo](https://github.com/msfjarvis/adnix-rs), I get a [Homebrew formula with a couple `depends_on ""` lines](https://github.com/msfjarvis/homebrew-tap/commit/91354a1c59fdce0db36ec97d27f5518bf55e90e0) that were not present with 0.2.0-prerelease.5 (sorry I hadn't upgraded this repo in a bit 😅)

**Comment by msfjarvis** [comment]
> Thanks for flagging this! I haven't seen this in our testing; I'll dig in. Checking your `Cargo.toml`, it looks like you're not using the system dependencies feature; is that right?

That's correct.

**Comment by mistydemeo** [comment]
Found the bug; this will be fixed in 0.4.0-prerelease.2.
