### ISSUE TITLE
-Ctarget-feature=+crt-static on musl builds

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/cargo-dist#486]
from https://github.com/axodotdev/cargo-dist/pull/483#issuecomment-1766970460 via @bjorn3

> Could you explicitly enable -Ctarget-feature=+crt-static? The intent is to switch the musl target to default to dynamic linking in the future. Having everyone who depends on musl statically linking explicitly specify this will make it easier to flip the switch in the future.

**Comment by Gankra** [comment]
@bjorn3 happy to flip crt-static (we do it for windows already) -- is there any movement towards a naming scheme to quickly distinguish "dynamic musl" from "static musl" in target triples? Vaguely mulling over cargo-dist referring to it as `unknown-linux-musl-static` or `unknown-linux-musl+static` to be clear about it.

**Comment by ashleygwilliams** [comment]
@bjorn3 reading https://github.com/rust-lang/compiler-team/issues/422#issuecomment-812135847 - it looks like we may need more than the suggested flag to maintain compatibility with the current behavior- is that true? also, thanks again for commenting with the heads up, it's very appreciated

**Comment by bjorn3** [comment]
> @bjorn3 reading https://github.com/rust-lang/compiler-team/issues/422#issuecomment-812135847 - it looks like we may need more than the suggested flag to maintain compatibility with the current behavior- is that true?

Good point. Using `-Clink-self-contained=yes` may also be necessary in the future if we decide to change the default for that to false too. Or alternatively you could install musl libc before compiling. Debian derived distros allow installing it next to glibc.

> is there any movement towards a naming scheme to quickly distinguish "dynamic musl" from "static musl" in target triples?

Not that I am aware of.
