### ISSUE TITLE
github ci should support manual triggering

### ISSUE THREAD

**Issue by Gankra** [axodotdev/cargo-dist#49]
If you add workflow_dispatch as an triggering event, the user can manually trigger it with a nice builtin form. This would be great for debugging/testing without having to drown your repo in prerelease git tags!

https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

**Comment by frol** [comment]
I think this issue is now implemented and configurable via [dispatch-releases](https://opensource.axo.dev/cargo-dist/book/reference/config.html#dispatch-releases).
