### ISSUE TITLE
Potential packaging issue with 0.4.0 (tests fail if rustup isn't installed)

### ISSUE THREAD

**Issue by msfjarvis** [axodotdev/cargo-dist#509]
These [cli tests](https://github.com/axodotdev/cargo-dist/blob/bd647c63feaf4ce2f8360523f3e6f38f1a959a61/cargo-dist/tests/cli-tests.rs#L81-L173) now require rustup to pass, since its absence adds a warning to the CLI output. I don't think this needs to be _fixed_ by cargo-dist, but I figured I'd leave a note here for other packagers for when 0.4.0 is out.

```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: cargo-dist/tests/snapshots/error_manifest.snap
Snapshot: error_manifest
Source: cargo-dist/tests/cli-tests.rs:169
────────────────────────────────────────────────────────────────────────────────
Expression: format_outputs(&output)
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
    0     0 │ stdout:
    1     1 │ {"diagnostic": {"message": "This workspace doesn't have anything for cargo-dist to Release!","severity": "error","causes": [],"help": "You may need to pass the curre>
    2     2 │ 
    3     3 │ stderr:
          4 │+ WARN You're trying to cross-compile for musl from glibc, but I can't find rustup to ensure you have the rust toolchains for it!
    4     5 │   × This workspace doesn't have anything for cargo-dist to Release!
    5     6 │   help: You may need to pass the current version as --tag, or need to give
    6     7 │         all your packages the same version
    7     8 │         
────────────┴───────────────────────────────────────────────────────────────────
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
test test_error_manifest ... FAILED

failures:

failures:
    test_error_manifest

FAIL [   0.045s] cargo-dist::cli-tests test_error_manifest
FAIL [   0.044s] cargo-dist::cli-tests test_lib_manifest
FAIL [   0.044s] cargo-dist::cli-tests test_lib_manifest_slash
FAIL [   0.044s] cargo-dist::cli-tests test_manifest
```

**Comment by Gankra** [comment]
Oh interesting, thanks for pointing this out!

Out of curiosity, which distro were you packaging for? If I recall correctly:

* Arch has had it for a while
* Nix has had it for a while
* Debian *just* added rustup to its tree, (although maybe that is so new that no one can use it yet?)
* Fedora explicitly/intentionally *doesn't* have it (same rationale as Debian had previously)

---

Is there an established practice for "hello yes I am a distro packager, adjust test expectations"? Trying to think of the best way for me to handle this without losing some desirable properties of the tests (the snapshots function as UI tests and I usually *do* want them to be this fussy/brittle for our CI).

**Comment by msfjarvis** [comment]
> Oh interesting, thanks for pointing this out!
> 
> Out of curiosity, which distro were you packaging for? If I recall correctly:
> 
>     * Arch has had it for a while
> 
>     * Nix has had it for a while
> 
>     * OpenSUSE has had it for a while
> 
>     * Debian _just_ added rustup to its tree, (although maybe that is so new that no one can use it yet?)
> 
>     * Fedora explicitly/intentionally _doesn't_ have it (same rationale as Debian had previously)
> 

It's Nix. I package the [pre-releases specifically](https://github.com/msfjarvis/custom-nixpkgs/blob/8f76a3277cdb828c5a0935668868bead24b7e596/pkgs/cargo-dist-unstable/default.nix) in my own repo so I can test those with my projects.

> 
> Is there an established practice for "hello yes I am a distro packager, adjust test expectations"? Trying to think of the best way for me to handle this without losing some desirable properties of the tests (the snapshots function as UI tests and I usually _do_ want them to be this fussy/brittle for our CI).

I've had this interaction with a couple projects:

1. If there's a test that can be adjusted to work within the sandbox easily, we send in a PR.
2. If it's not possible to run it in the sandbox (needs network, global file access and such), we skip the specific test.

For cargo-dist, Nixpkgs [already removes](https://github.com/NixOS/nixpkgs/blob/545857e74921a41af587931bd80dfed5541c3cbf/pkgs/development/tools/rust/cargo-dist/default.nix#L49-L52) the [integration tests](https://github.com/axodotdev/cargo-dist/blob/main/cargo-dist/tests/integration-tests.rs) since they require network access, we can also skip these specific ones if it's necessary. Admittedly I didn't try the simpler solution of just adding rustup as a build input since I assumed it would try to install the relevant toolchain which would still fail anyway but I can try that in a couple hours.

**Comment by msfjarvis** [comment]
Adding `rustup` to the test environment does make the tests pass, so I've made the change for the upstream Nix package as part of the v0.4.0 bump: https://github.com/NixOS/nixpkgs/pull/263382

**Comment by Gankra** [comment]
(gonna leave this open for like a week so it's easy to find, then close as resolved)
