### ISSUE TITLE
Class name for homebrew formula truncates `s` incorrectly

### ISSUE THREAD

**Issue by lukexor** [axodotdev/cargo-dist#541]
Inputting app name as `tetanes` results in `Tetane`

Seems like it's attempting to singularize the class name - but there are a lot of words that end with `s`.

Not sure if this has any impact on the actual homebrew formula installation or not.

**Comment by mistydemeo** [comment]
Oh interesting! That's an unexpected bug. I'll look into this, thank you.

**Comment by mistydemeo** [comment]
I have a fix that should make our next bugfix release. I've used your app's name as a test case to ensure it'll work.

**Comment by mistydemeo** [comment]
This should be fixed in the new 0.4.3 release. Thanks again for the report!
