### ISSUE TITLE
Installer.sh sourcing ~/.cargo/bin in ~/.profile is not always sufficient

### ISSUE THREAD

**Issue by sts10** [axodotdev/cargo-dist#547]
Hi folks! Love the project! 

I'm excited to have released my latest Rust project, a passphrase generator called Phraze, with cargo-dist v0.4.2. [Here's the first release that uses cargo-dist](https://github.com/sts10/phraze/releases/tag/v0.3.3). I checked the box for a shell script install otpino, and sure enough I get the pretty "Install prebuilt binaries via shell script" one-liner in my release notes for users to paste into their terminals: `curl --proto '=https' --tlsv1.2 -LsSf https://github.com/sts10/phraze/releases/download/v0.3.3/phraze-installer.sh | sh`

Excited to a make it easier for non-Rust devs to use my Rust tool, I booted up another machine of mine that runs Debian but doesn't have Rust or Cargo installed. (In a sense this is my targeted user for why I choose to use cargo-dist -- if the user has Cargo installed, they can just use cargo to install my program!) 

## Expected behavior 

I had my fingers crossed that, on that machine, I could simply run the `curl` one liner and then, poof, use my passphrase generator. 

Since I didn't have a `~/cargo` directory (or Cargo installed) on this particular machine, I just assumed that the script would install my executable elsewhere, likely somewhere already in this machine's PATH. 

When I ran the script, it told me the program had been installed successfully to `~/.cargo/bin`. I was suspicious since, not having Cargo installed on this machine, I knew that directory wasn't in PATH. I did also get some kind of message to `source` something... (I'm really sorry that I can't recreate this right now), but I figured it was just telling me to restart my terminal (a fair request). 

I then expected to be able to run `phraze` and have it work.

## Observed behavior
I tried running `phraze` but I got a command not found error. Even starting the terminal again, same thing: command not found. 

Just to check, when I ran `echo $PATH`, `~/.cargo/bin` was not in the PATH. 

## Suggestions

I was hoping that when the installer.sh script would have detected that `~/.cargo/bin` was NOT in the current PATH, the script would (A) install the executable to /usr/local/bin or somewhere already in the PATH; (B) automatically add `~/.cargo/bin` to the user's PATH (maybe writing the end of ~/.bashrc); or (c) Print to screen a very clear message like "To finish installation of <program name>, run: `echo "export PATH = "$HOME/.cargo/bin:$PATH" >> ~/.bashrc && source ~/.bashrc` or something. (I think the Rust install script does something like option C?) 

To generalize, I think that if the installer script installs the executable to a directory NOT currently in the PATH, it should, at minimum, print clear, next-step instructions on how to add the directory to the PATH. Otherwise a user may get/feel lost when confronting the "command not found" message when they first try to run the program.

I hope this makes sense -- in a bit of a hurry right now, but I can investigate further tomorrow.

**Comment by mistydemeo** [comment]
Thanks so much for the detailed report!

> automatically add ~/.cargo/bin to the user's PATH (maybe writing the end of ~/.bashrc)

We currently try to do this; if we install to a location that's not on the user's `PATH`, we drop something into `~/.profile`, which is read by certain shells. Can you confirm if that file is there and if a line was added there to source something to add it to your `PATH`?

Secondly, can you confirm whether opening a new shell after installing results in `phraze` being on your `PATH`?

And, finally - I think you're right that `~/.cargo` is an unexpected place for users who don't have cargo/rustup/rust installed.

**Comment by sts10** [comment]
I'm going to answer these out of order for hopefully more clarity rather than less.

> can you confirm whether opening a new shell after installing results in phraze being on your PATH?

Opening a new Terminal does **not** result is phraze in being on my PATH. Gives `bash: phraze: command not found`. Same thing after a reboot: command not found.

> We currently try to do this; if we install to a location that's not on the user's PATH, we drop something into ~/.profile, which is read by certain shells. Can you confirm if that file is there and if a line was added there to source something to add it to your PATH?

Here's my entire `~/.profile`. The file itself -- `~/.profile` -- was created when I installed this Linux distro (early October). But it appears to have been modified when I ran our `curl` command.
```bash
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
. "$HOME/.cargo/env"
```

I think it's safe to assume that my Phraze installation attempt added that last line: `. "$HOME/.cargo/env"`. While I don't understand that leading `.`, running this command on its own in a fresh terminal DOES add `~/.cargo/bin` to my PATH, and enables Phraze to run correctly when user runs `phraze`. 

(Note that neither a `~/.bash_profile` nor a `~/.bash_login` file exist on this machine, which, according to the comment in the file, means that this `~/.profile` _should_ be read.)

I think the issue is spelled out in this comment: "~/.profile: executed by the command interpreter for login shells."

My understanding is that, when a typical user opens a Terminal window, that is known as "interactive non-login shell"; and thus `~/.profile` is not run in this case.

Here's one way I proved that to myself:
```text
$ phraze
bash: phraze: command not found
$ source ~/.profile
$ phraze 
#=> success! Passphrase produced.
```

I'm still not sure what a "login shell" (or "interactive login shell") is or when it's used by a Linux system. Maybe it's read at login, but the fact that this machine still isn't finding `phraze` after a reboot confirms to me that `~/.profile` is not being read in a way that alters PATH in a typical Terminal shell, exactly where I want a prospective user to have access to the `phraze` command.

**Comment by Gankra** [comment]
`.` is very confusingly the original and more portable version of `source` (in user-facing messages we tell you to use `source` because it's too easy to miss the `.`, but when emitting it to env files we use the more portable `.`).

Our implementation is based on the one on rustup, but I conservatively implemented a subset of their functionality (guess it's time to implement more of it).

Specifically we blast `. "$HOME/.cargo/env"` into `~/.profile`, but rustup also shotgun blasts it into various bash rcfiles:

https://github.com/rust-lang/rustup/blob/b5d74ac69307de29cee586c779bdb6b3aee7f7af/src/cli/self_update/shell.rs#L138-L144

And zshenv files:

https://github.com/rust-lang/rustup/blob/b5d74ac69307de29cee586c779bdb6b3aee7f7af/src/cli/self_update/shell.rs#L186-L191

**Comment by sts10** [comment]
Yeah, it'd be nice if ~/.profile was just a nice, shell-agnostic (BASH, zsh, fish, etc.) place for stuff like this, but maybe we (still) need the shotgun blast technique in this case.

**Comment by martindisch** [comment]
I had a test group of people with macOS (no Rust toolchain) and can confirm your observations.

Specifically:
- The default shell on the system (Zsh) doesn't consider `.profile` at all, it wants `.zprofile`
- The profile may not be the best place anyway, as it's often only sourced on login (with some exceptions according to [this](https://www.zerotohero.dev/zshell-startup-files/)), so it doesn't work as expected for people opening a new terminal after installation

It looks like aligning with what rustup does, ugly as it may be, is the most robust approach.

Fantastic project you've got here by the way, it's my favorite thing this year. Exactly what I've been looking for!

**Comment by mistydemeo** [comment]
I'm planning on extending this to write to a number of other config files.

> The profile may not be the best place anyway, as it's often only sourced on login (with some exceptions according to [this](https://www.zerotohero.dev/zshell-startup-files/)), so it doesn't work as expected for people opening a new terminal after installation

This part isn't a big deal: on macOS, at least, every shell is a login shell by default.
