### ISSUE TITLE
readme for crates.io

### ISSUE THREAD

**Issue by ashleygwilliams** [axodotdev/cargo-dist#55]
currently the README for cargo-dist sits at the workspace root so that it is displayed in github, however, this prevents it from being displayed on crates.io as it is not in the default position (at the root of the crate project). 

based on the cargo manifest docs, the readme path has to be relative to the project root, so i think we could fix this using `../README.md`.

however we could also fix this by changing the organization from a "flat workspace" (workspace -> crates) to a "nested workspace" (app/workspace -> crates) where the cargo dist bin app sits on the top level and then has a nested workspace for the schema crate (and any other future workspace items). 

curious what your pref is @Gankra - i think i sorta prefer the "nested workspace" because the workspace is in support of the main application, so it feels more semantically accurate.

**Comment by Gankra** [comment]
this is fixed in #50 already

**Comment by Gankra** [comment]
I personally prefer the current architecture, rust-minidump used to have nesting and it caused weird problems that I can't remember the details of anymore.

**Comment by ashleygwilliams** [comment]
whoops, sorry for not catching it in that PR, apologies. sounds good, closing this
