### ISSUE TITLE
0.4.3 release not on crates.io or in CHANGELOG

### ISSUE THREAD

**Issue by jwodder** [axodotdev/cargo-dist#562]
There is [a GitHub release for cargo-dist 0.4.3](https://github.com/axodotdev/cargo-dist/releases/tag/v0.4.3), but there is no cargo-dist 0.4.3 on crates.io, and the changelog in this repository doesn't list any changes past 0.4.2.

**Comment by Gankra** [comment]
Thanks for catching this! It was a backport release (have some WIP stuff on main), so we forgot a couple things on the release checklist.
