### ISSUE TITLE
properly detect if "init" hasn't been run

### ISSUE THREAD

**Issue by Gankra** [axodotdev/cargo-dist#63]
The only reason you "must" run init is to ensure --profile=dist works. I don't think there's any way to ask cargo if that profile is defined, so there are three options:

* parse the Cargo.tomls and try to find the definition (will erroneously fail if the profile is specified totally globally... but also that won't work when checked in anyway so they're still wrong?)
* ??? is there some info in cargo-metadata about defined profiles ???
* parse the error message from rustc/cargo for the "hey the dist profile doesn't exist" to provide a better diagnostic

**Comment by ashleygwilliams** [comment]
i think parsing the cargo-toml here feels right to me though i'll admit i didn't even consider that someone would define the profile globally. is that a thing people commonly do? regardless, if a globally defined profile *won't* work, it stands to reason that not being able to detect it by reading the cargo.toml is a *feature*. 

as an aside "cargo-metaprofile" is available on crates.io
