### ISSUE TITLE
Update for v4 of the upload- & download-artifact actions

### ISSUE THREAD

**Issue by jwodder** [axodotdev/cargo-dist#653]
The GitHub Actions workflow generated by `cargo-dist` currently uses v3 of [`actions/upload-artifact`](https://github.com/actions/upload-artifact) and [`actions/download-artifact`](https://github.com/actions/download-artifact).  v4 of these workflows was released on December 14 (["What's New" documentation](https://github.com/actions/toolkit/tree/main/packages/artifact#v2---whats-new)), so you'll probably want to update the workflow at some point.

**Comment by Gankra** [comment]
oh loooord this is a huge semantic update to the artifacts update that we are extremely not compatible with right now, this is gonna be annoying...

**Comment by Gankra** [comment]
coming back to this, i think the properties we need from artifacts can still be preserved using the v4 API, thanks to the download-artifacts action supporting bulk merged downloads of artifacts:

https://github.com/actions/download-artifact#download-all-artifacts

So plan of action for this would be:

* give each job a unique "name" (we already *mostly* do this for dist-manifests!)
  * I think the only remaining conflicts are that `plan` and `host` try to use an unadorned name, we should just make them use different names... and tell `announce` to use the `host` one.
* have each job upload to `artifacts-{name}`
* have each job download `pattern: artifacts-*` with `merge-multiple: true`
