### ISSUE TITLE
Conflict: an artifact with this name already exists on the workflow run

### ISSUE THREAD

**Issue by ckoehler** [axodotdev/cargo-dist#656]
Hey there,

I'm fairly new to GH Actions, and am getting this error in the `build-local-artifact` and `build-global-artifacts` jobs:

```
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```

I've got 4 `build-local-artifact` jobs, for 4 architectures, and on the first run all 4 failed with this error. Re-running failed jobs a few more times got me one more of these passing each time, with no other changes. Same for the `build-global-artifacts` job: it succeeded on rerun. 

Thanks!

**Comment by ckoehler** [comment]
Hm I see that cargo-dist 0.6.0 was just released. I was running 0.5.0, but also the newer actions I think: 

`uses: actions/upload-artifact@v4`

Maybe this is related....

**Comment by ckoehler** [comment]
Yes, dependabot updates it. I'll make sure to go back to 3 and turn that part off. Thanks for confirming!

**Comment by mistydemeo** [comment]
You're welcome! I'd recommend making sure dependabot ignores those generated files. cargo-dist's CI should fail on those dependabot PRs too, since the file on disk will no longer match cargo-dist's generated content.

**Comment by ckoehler** [comment]
Ha! It did fail but I allowed it with a config option from CI. Shows what I know...
