### ISSUE TITLE
`cargo dist build --artifacts=local` builds extra artifacts?

### ISSUE THREAD

**Issue by max-heller** [axodotdev/cargo-dist#658]
It seems like `cargo dist build --artifacts=local` builds artifacts specified in [`extra-artifacts`](https://opensource.axo.dev/cargo-dist/book/reference/config.html#extra-artifacts) in addition to local artifacts--is this intentional? My impression was that `--artifacts=local` would not build `extra-artifacts`, while `--artifacts=global` would.

**Comment by mistydemeo** [comment]
Interesting - that's not expected, and not what I'm currently seeing while testing with cargo-dist itself. Is this a public repo I could take a look at?

**Comment by max-heller** [comment]
> Is this a public repo I could take a look at?

Yep! [Here's an example job](https://github.com/max-heller/mdbook-pandoc/actions/runs/7268222399/job/19803644834?pr=27#step:7:239). It also appears to be happening in [this cargo-dist job](https://github.com/axodotdev/cargo-dist/actions/runs/7255682300/job/19766742088#step:7:264). Both of these are in `build-local-artifacts` jobs [which pass `--artifacts=local`](https://github.com/max-heller/mdbook-pandoc/actions/runs/7268222399/job/19803644834?pr=27#step:7:3).

**Comment by mistydemeo** [comment]
I've figured out what's causing this - I'm looking into a fix. Most likely, it'll land in a 0.6.1 point release.
