### ISSUE TITLE
Failed to generate a source tarball for project

### ISSUE THREAD

**Issue by waynelabsio** [axodotdev/cargo-dist#695]
Hi, thank you for making cargo-dist happens. This was really needed. Filing a small bug:

This is likely an edge case that got missed, but it happens in a fresh git project with no commits.

Command ran: `cargo dist build`

Error log:
```
fatal: not a valid object name: HEAD
  × We failed to generate a source tarball for your project
  help: This is probably not your fault, please file an issue!
```

Adding a commit to the git project, makes it go away.

**Comment by mistydemeo** [comment]
Good catch, thank you! I hadn't considered this usecase. We check whether you're running in a directory that isn't a git repo, but we don't check whether you're in a repo that has no commits. I'll fix this.

**Comment by mistydemeo** [comment]
This is fixed; we'll have the fix in an upcoming release. Thanks again for your report!
