### ISSUE TITLE
 package cannot be built because it requires rustc 1.75 or newer, while the currently active rustc version is 1.74.1   

### ISSUE THREAD

**Issue by nbittich** [axodotdev/cargo-dist#701]
:-( 
https://github.com/nbittich/adana/actions/runs/7466354747/job/20317545040

**Comment by nbittich** [comment]
I have one, is there something incorrect I missed? https://github.com/nbittich/adana/blob/master/rust-toolchain.toml

**Comment by mistydemeo** [comment]
I think that file's not correctly formatted. The docs I linked above don't mention a `host` field, and `channel` is what's used to select the version. If I clone your repo locally, rustup won't pick 1.75 for me either; I had to set `channel` to `1.75` for rustup to pick the version you want.

**Comment by nbittich** [comment]
Oh I see! I probably took that from a bad example in the past, but idd after I've updated the file with your recommendation, it fixed the  issue. Thanks for your help!

**Comment by mistydemeo** [comment]
You're welcome! Please let us know if you have any other problems.
