### ISSUE TITLE
Link to schema docs when you find invalid configuration

### ISSUE THREAD

**Issue by LukeMathWalker** [axodotdev/cargo-dist#707]
`cargo-dist`'s errors are _excellent_ when it runs into invalid configuration.
I ran into this while configuring `cargo-dist` for Pavex:

```
 × Malformed metadata.dist in /home/runner/work/pavex/pavex/libs/Cargo.toml
  ╰─▶ invalid type: boolean `true`, expected a sequence
```

The natural follow-up question: a sequence? What can I set there?
It'd be nice to include a link to your [configuration reference](https://opensource.axo.dev/cargo-dist/book/reference/config.html) in that error, rather than having to Google it (and that's because I knew it existed in the first place).

**Comment by ashleygwilliams** [comment]
hey @LukeMathWalker this is a great suggestion. if you are at all interested in contributing we'd be happy to help point you in the right direction- but regardless i think this is a good addition and we'll work to get it in!

**Comment by LukeMathWalker** [comment]
Here you go 😁 
https://github.com/axodotdev/cargo-dist/pull/709

**Comment by ashleygwilliams** [comment]
aw yay! thank you, will take a look momentarily!
