### ISSUE TITLE
Selection of runner for Github CI

### ISSUE THREAD

**Issue by MrHedmad** [axodotdev/cargo-dist#749]
Hello! I maintain [this binary](https://github.com/MrHedmad/kerblam) and I've noticed that while compiling Rust links to `libssl.1.1` (see [this issue](https://github.com/MrHedmad/kerblam/issues/42)) instead of a newer `libssl.3.x`.
I've looked around and I believe that the issue is `cargo-dist` as it uses the Github runner `ubuntu-20.04` (as found in my own `dist-manifest.json` and the [example one that you provide](https://github.com/axodotdev/axolotlsay/releases/latest/download/dist-manifest.json)). The runner (and I tested this manually) pulls in the `openssl` library version 1.1, not 3.x.

Using a different runner (e.g. `ubuntu-latest`) fixes the issue. I cannot find issues related to the selection of the runner environment or any information about it in the documentations.
In any case, if Ubuntu 20.04 is the default runner (maybe hardcoded?), I believe that upgrading to the latest LTS ([Ubuntu 22.04](https://discourse.ubuntu.com/t/jammy-jellyfish-release-notes/24668)) is a fair choice.

How can I select a different runner for the `x86_64-unknown-linux-gnu` target? Thank you.

**Comment by Gankra** [comment]
So we do hardcode to the oldest possible runner we can find specifically *to* link against the oldest possible libraries. In particular we want to link against the oldest possible glibc, so that the linux-gnu binaries are as portable as possible (for instance, iirc github codespaces defaults to running on 20.04, so binaries built on 22.04 fail to run there 😭).

Also just checking: you do *for reals* want to be linking openssl, yeah? Most rust projects try to avoid this, opting to statically link rust-tls: https://github.com/axodotdev/gazenot/blob/ef900eca9c9c8309290b303faebae85cafebf9c5/Cargo.toml#L31-L35

**Comment by Gankra** [comment]
(I'm not opposed to having settings to bump up the runners, just first checking that it actually solves your problem)

**Comment by MrHedmad** [comment]
I'm a Rust beginner so I'm still not familiar with all of this linking issues. But if I can avoid relying on `opensll` of course it would be best. The only issues I got when including `openssl` (see [here](https://github.com/MrHedmad/kerblam/pull/43)) is that the binary size baloons. But I had no idea that `reqwest` can use something else entirely, as you show. I'll try it ad check binary sizes. But I think that probably fixes the issue.

Still, maybe an obscure option somewhere to set the runners might still be useful to someone, at some point!

**Comment by MrHedmad** [comment]
I've added the `rustls-tls` feature to `reqwest` and the binary size is identical. Still need to try it out but I guess that solves my issue! I'll leave closing to you; maybe you wish to still include the option to change runners.

Thank you for the ultra-fast reply!

**Comment by mgattozzi** [comment]
I also ran into a similar issue today as I need to use a version of protoc via apt from Ubuntu 22.04 or later as we use a flag not available on 20.04. I can set them manually, but it's not the most ideal. However, I do understand linking to an older glibc as this has been an issue at other jobs. Being able to have that choice would be nice.

**Comment by ashleygwilliams** [comment]
@mgattozzi thanks for filing! i did not even consider that system deps would be keyed to ubuntu version and therefore runner- though now that you mention it it makes perfect sense. out of curiosity - would you be able to achieve what you want with our custom runners config? https://opensource.axo.dev/cargo-dist/book/reference/config.html#github-custom-runners

**Comment by mgattozzi** [comment]
As long as I can put ubuntu-latest that should work. I can give it a shot later and report back 😁

**Comment by ashleygwilliams** [comment]
@mgattozzi def curious to hear how it goes- it's kinda a hidden feature in the config right now with a name that's a little too impl specific- if it *doesn't* work, that is almost certainly a bug, so let us know!

**Comment by mgattozzi** [comment]
@ashleygwilliams looks like it did exactly what I wanted. You can see the plan output the right values [here](https://github.com/influxdata/influxdb/actions/runs/8240180696/job/22535062018#step:4:362) and the correct version of protoc installed [here](https://github.com/influxdata/influxdb/actions/runs/8240180696/job/22535072412#step:6:29). Thanks for the tip 😄

**Comment by mgattozzi** [comment]
Which I think means this issue could be closed given I could set the CI runner I wanted.

**Comment by gc-victor** [comment]
Hi! I'm having a similar issue, but with Docker using `FROM debian:12-slim` on Fly.io.

`error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

**Comment by gc-victor** [comment]
I have solved it adding `vendored-openssl`.

**Comment by MrHedmad** [comment]
Hey @gc-victor - just saying that if the issue is related to `reqwest`, you can add the `rustls-tls` feature flag by editing the `cargo.toml` file as in here:

> I've added the `rustls-tls` feature to `reqwest` and the binary size is identical. Still need to try it out but I guess that solves my issue! I'll leave closing to you; maybe you wish to still include the option to change runners.
> 
> Thank you for the ultra-fast reply!

I.e. write this:
```toml
[dependencies]
reqwest = { version = "^0.11", default-features = false, features = ["rustls-tls"] }
```
You must disable `default-features` since there is currently no way to set mutually-exclusive features, so you need to turn off the `default-tls` feature to not link against the library in question ([the only default feature of `reqwest`](https://docs.rs/crate/reqwest/latest/features)).

Using `vendored-openssl` makes your binary huge, so it's best to just use `rustls-tls`.
Hope this helps shed some light on the issue (and we can let this post necrose :D)
