### ISSUE TITLE
Allow publishing under bin name instead of package name

### ISSUE THREAD

**Issue by MarinPostma** [axodotdev/cargo-dist#777]
Hello!

We want to publish our binary on homebrew under the binary name, but it is published under the crate name. Is there a way to do that?

**Comment by mistydemeo** [comment]
We don't currently support this, but we can look into adding it in the future.

**Comment by MarinPostma** [comment]
Do you think there is a workaround in the meantime? Our issue is that we changed the crate name in our repo, and cargo dist added a new formula to our homebrew, with the new name, meaning that the official formula is not getting new releases.

My guess is that something could be worked out here: https://github.com/tursodatabase/libsql/blob/main/.github/workflows/release-libsql-server.yml#L250-L262, but I'm not 100% sure how all of that works.

**Comment by ashleygwilliams** [comment]
got an impl up if you want to take a look @MarinPostma
