### ISSUE TITLE
Homebrew publish fails tests

### ISSUE THREAD

**Issue by ucodery** [axodotdev/cargo-dist#810]
Hi, I am new to cargo-dist but already a super fan! I am trying to figure out how to publish my app as a brew formula and have got as far as I can with the docs. This is my first time using cargo-dist and my first time managing my own brew tap, so it is entirely possible that I did something wrong.

I have successfully got my Rust project committed to my homebrew project but this triggers brew tests in CI that fail on the new Formula file. The `brew test-bot` command ultimately fails ([here](https://github.com/ucodery/homebrew-draft/actions/runs/7995352292/job/21835482798)) with
```
1 file inspected, 9 offenses detected, 7 offenses autocorrectable
```
I'm sure I could fix these mistakes but I am worried they would reappear on the next dist publish.

To get here I ran
```
brew tap-new
```
and uploaded that one commit. nothing else in the homebrew repo.
On the app repo I added `tap` and `publish-jobs` and bumped the version in Cargo.toml, then ran
```
cargo dist generate ci --check
```
and uploaded with a new tag (and added a repo secret).

That led to a new formula file in my homebrew repo, but the above-mentioned failure.

**Comment by ashleygwilliams** [comment]
interesting! let me take a look at this

**Comment by ashleygwilliams** [comment]
this is very neat and i think we can both fix these issues, but also add this tooling to our own tests to make sure we're generating formulae that pass.

before i dive in- are you at all interested in contributing some/all of these changes? would be happy to point you in the right direction if so- if not no worries!!

**Comment by ucodery** [comment]
@ashleygwilliams I am interested in making the changes. brew's suggestions seem very straightforward and reasonable. I just wanted to confirm it was a real issue with the code first (and not maybe that I read docs wrong).

**Comment by ashleygwilliams** [comment]
yup! i agree the changes seem very straightforward and reasonable. our inhouse brew expert @mistydemeo is on vacation, and so i'd want to have her review before we merged anything, but we are all cargo fmt fans here, and this seems like that for brew- hard for me to quibble with it! i do think the corrected code will likely end up behaving the same way as the current code but i like following standards, especially tool-enforced ones.

**Comment by ucodery** [comment]
Hmm, so I see that the 2 not-autocorrectable issues were that I was missing metadata in my Cargo's `[package]`. I think the docs need to be updated to mention that `description` and `homepage` are used (working on that). However, the publishing should probably be blocked on these fields being present if `publish-jobs` includes `"homebrew"`. WDYT? I believe a similar situation happens for `repository`, where cargo build will work if that field is left out, but cargo dist blocks, asking the dev to fill it in. Trying to see where that check could go..

**Comment by ashleygwilliams** [comment]
i think this sounds reasonable to me! we have similar checks/requirements for the MSI installer, which requires the authors field in Cargo.toml!

**Comment by ashleygwilliams** [comment]
the best place for checks is the "plan" step- as generally that will run before a user is even thinking about releasing (which is good!). it can be a bit abrasive to get hard errors during a release

**Comment by ashleygwilliams** [comment]
btw- if you are on our discord (https://discord.gg/q7zqx44Pma) feel free to ping me (@ag_dubs)! (i'm about to head out but will definitely be around tomorrow)

**Comment by ucodery** [comment]
Fix in https://github.com/axodotdev/cargo-dist/pull/818
