### ISSUE TITLE
Support npm for clis

### ISSUE THREAD

**Issue by untitaker** [axodotdev/cargo-dist#82]
Building npm packages that wrap rust cli tools is hard to get right in a secure way. I know of the following repos that do this:

https://github.com/getsentry/sentry-cli
https://github.com/cloudflare/wrangler
https://github.com/untitaker/hyperlink

**Comment by Gankra** [comment]
This will be shipping in 0.0.6 ~today

* #210 
* #228 
* #224 
* https://opensource.axo.dev/cargo-dist/book/installers.html#npm (docs will only go live when we cut the release)
