### ISSUE TITLE
Homebrew: improve license field handling

### ISSUE THREAD

**Issue by mistydemeo** [axodotdev/cargo-dist#820]
While Homebrew uses SPDX licenses, it doesn't parse the full SPDX grammar. Rather, it [uses a Ruby DSL](https://docs.brew.sh/License-Guidelines#complex-spdx-license-expressions) to express the relationships between licenses. Cargo, meanwhile, uses SPDX strings directly, so that's what we pass through to the Homebrew formula. This is mostly harmless: it means Homebrew won't be able to provide detailed information about the license, but there's very little harm to it. If we felt like it though, we could use the [spdx crate](https://crates.io/crates/spdx) to parse the field from Cargo.toml and output the specific format that Homebrew expects. It's a nice-to-have, but not essential.

What we do now:

```ruby
license "MIT OR Apache-2.0"
```

What Homebrew expects:

```ruby
license any_of: ["MIT", "Apache-2.0"]
```

**Comment by cxreiff** [comment]
Just linking this here, I broached the subject of adding this parsing on the Homebrew side to align with other package managers:

https://github.com/orgs/Homebrew/discussions/5561

Homebrew has a private function for doing this parsing, but its only being used for a specific use case (not parsing ruby formulas):

https://github.com/Homebrew/brew/blob/277c4259fb5326fa13dc8d132b986be21c333b97/Library/Homebrew/utils/spdx.rb#L127-L159
