### ISSUE TITLE
"which"

### ISSUE THREAD

**Issue by dhduvall** [axodotdev/cargo-dist#828]
The installer script [claims to require](https://github.com/axodotdev/cargo-dist/blob/921b6b243d42f09b80506904e895f59a71008d42/cargo-dist/templates/installer/installer.sh.j2#L84) the `which` command, but `which` is never used. Not all images have `which`, so the script can fail unnecessarily.

As a workaround, I'm simply doing `curl https://.... | grep -v "need_cmd which" | sh`, which at least is not too bad for now.

**Comment by mistydemeo** [comment]
Nice catch. I'll fix this.
