### ISSUE TITLE
optional feature for cargo-dist to vendor its dependent third-party actions

### ISSUE THREAD

**Issue by Gankra** [axodotdev/cargo-dist#839]
This would make locked down or security-focused projects happier.

I'm.... not entirely sure if there's like, legal implications... but cargo-vendor exists so I guess it's fine?

Mozilla did this for dump_syms, so we at least have proof you *can* do it:

https://github.com/mozilla/dump_syms/commit/ce71847c0781f264a398d611763bdf3d0949b591

**Comment by Gankra** [comment]
@gabrielesvelto was there a tool/process you followed for this or did you like, literally clone their repo and copy the files over

**Comment by gabrielesvelto** [comment]
I literally cloned the repo and copied the files over, though in all fairness I could have just downloaded the last release tarball and used that.

**Comment by skade** [comment]
I like the vendoring option, particularly for code preservation.

As much as I love automatism, I’d be fine with with checking the licensing ourselves. At quick glance, cargo-dist making the whole process easier and as a first step calling out that it does not do license checking, it would be okay.

Also, many of the licenses people avoid (mainly GPL) should not be of relevance here, as the actions don’t become part of the artifact.

**Comment by gabrielesvelto** [comment]
I noticed that in the latest versions of cargo-dist the ncipollo/release-action 3rd party action is not required anymore, so I could drop the hack I used to vendor it.

**Comment by Gankra** [comment]
Yep!

**Comment by mistydemeo** [comment]
I'm going to close this since we ended up removing our usage of third-party actions altogether.
