### ISSUE TITLE
Support for multiple Windows architectures in installer.ps1

### ISSUE THREAD

**Issue by AustinWise** [axodotdev/cargo-dist#85]
While x86_64 is the most popular architecture for Windows at this time, ARM64 is slowly gaining relevance and x86 remains useful for certain scenarios.

I propose adding the ability for the installer script to automatically pick the best executable from those available when installing. The `dist-manifest.json` file already contains all the information needed to pick the best version. Building and uploading the different version for Windows architectures is a separate issue.

I have some ideas on how to approach this based on writing a [similar script](https://github.com/AustinWise/smeagol/blob/master/site/install.ps1). There are [some details](https://github.com/AustinWise/smeagol/blob/master/PowershellNotes.md) about this issues I ran into.

### Level One: download artifacts that match the current native OS architecture

There are a number of different ways to figure out the current OS native architecture:

* The [`RuntimeInformation`](https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.runtimeinformation.osarchitecture). This is the easiest way to get the architecture. On the latest versions of Windows and Power Shell Core, it tells the truth. On earlier versions, it might return X64 on ARM64. Given that ARM64 Windows can run X64 in emulation, it's probably fine to use this. Added in .NET 4.7.1.
* [`Environment.Is64BitOperatingSystem`](https://learn.microsoft.com/en-us/dotnet/api/system.environment.is64bitoperatingsystem) - added .NET 4 (so available in PowerShell 5). This can be used as a fallback to `RuntimeInformation` to detect 32-bit x86 Windows running older operating systems.

There are some native APIs that are probably not worth the complexity of calling from PowerShell:
 
* [`IsWow64Process2`](https://learn.microsoft.com/windows/win32/api/wow64apiset/nf-wow64apiset-iswow64process2). Returns accurate information about the system. Available starting in Windows 10 v1511.
* [`GetNativeSystemInfo`](https://learn.microsoft.com/windows/win32/api/sysinfoapi/nf-sysinfoapi-getnativesysteminfo)
  Added in Windows XP. Lies about the native system when running under x86 emulation on ARM64 and in ARM64EC processes.

### Level Two: downloading the best artifact, taking into account emulation.

If there is not an artifact that matches the current system's OS, it's possible an artifact of a different architecture may be runnable under emulation. For example, Windows 11 ARM64 systems can run X86, X64, and sometimes ARM32 executables.

In practice, falling back to x64 would is probably acceptable. 32-bit OS installs are pretty rare and ARM64 installs can run X64.

For completeness, on Windows 11 you can use [`GetMachineTypeAttributes`](https://learn.microsoft.com/windows/win32/api/processthreadsapi/nf-processthreadsapi-getmachinetypeattributes) to test to see what architectures are supported.

**Comment by frol** [comment]
MacOS aarch64 is getting popular even faster, and I agree that the installer could be just a bit smarter and consider compatible packages.

**Comment by Gankra** [comment]
Oh forgot to reply to this but 100% the ps installer should have all the same functionality as the shell installer

**Comment by AustinWise** [comment]
Cool, I updated the issue text with some different options for figuring out what architecture to download. Probably detecting the OS platform with the [`RuntimeInformation`](https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.runtimeinformation.osarchitecture) class is a good place to start.

**Comment by AustinWise** [comment]
I tested out the installer 0.11.1 today and it worked correctly. That is it installed the x64 version on my x64 Windows computer and the ARM64 version on my ARM64 Windows computer. Thanks!
