### ISSUE TITLE
How to install packages managed by `homebrew/cask`?

### ISSUE THREAD

**Issue by ChanTsune** [axodotdev/cargo-dist#850]
I tried to install `macfuse` with the following setting.
```
[workspace.metadata.dist.dependencies.homebrew]
macfuse = { stage = ["build", "run"] }
```

However, the following errors are reported.
```
Warning: 'macfuse' formula is unreadable: No available formula with the name "macfuse".
Warning: No available formula with the name "macfuse"
It was migrated from homebrew/core to homebrew/cask.
You can access it again by running:
  brew tap homebrew/cask
And then you can install it by running:
  brew install --cask macfuse
Installing macfuse has failed!
Homebrew Bundle failed! 1 Brewfile dependency failed to install.
Error: Process completed with exit code 1.
```

I checked the documentation but could not find a way to do so.

If `cargo-dist` don't support it, I willing to help make it available.

**Comment by mistydemeo** [comment]
Since macfuse isn't in homebrew/core, you need to specify the fully-qualified name in your dependencies: `homebrew/cask/macfuse`.

**Comment by ChanTsune** [comment]
thank you @mistydemeo !

I tried changing the package name to "homebrew/cask/macfuse" as you suggested, but the following error was reported and I could not install it.

```
Installing homebrew/cask/macfuse
Warning: 'homebrew/cask/macfuse' formula is unreadable: No available formula with the name "homebrew/cask/macfuse".
Warning: No available formula with the name "homebrew/cask/macfuse".
Installing homebrew/cask/macfuse has failed!
Homebrew Bundle failed! 1 Brewfile dependency failed to install.
```

Brewfile used to install dependencies has a special syntax for installing cask packages, so I guess that cargo-dist need to use it.

```brewfile
brew "package" <- cargo-dist only supports this

cask "cask_package" <- I guess need to use this
```

**Comment by mistydemeo** [comment]
I've opened a PR to generate proper brewfiles for this; it should be fixed in the next cargo-dist release.

**Comment by ChanTsune** [comment]
Thank you @mistydemeo !
I looking forward to the next release!
