### ISSUE TITLE
Copyright year not current

### ISSUE THREAD

**Issue by tshepang** [axodotdev/cargo-dist#882]
Saw `2022-2023` at top of a CI file. I hear the year is not needed, which would remove the need to keep it current.

**Comment by ashleygwilliams** [comment]
I saw this the other day as well! I think for our case we do need it, and since contributions have been made in all 3 years (2022-2024) we should update it to 2024. Thanks for filing- if you are interested in making the PR go for it, otherwise I'll get to it today :)

**Comment by tshepang** [comment]
[did it just for the CI file](https://github.com/axodotdev/cargo-dist/pull/883), because I don't know how other parts of the snapshot files are populated... they still have 2023 in them

**Comment by ashleygwilliams** [comment]
oh hrm- where is the 2023 in the other snapshot files? am multi-tasking but if you send me a link i can probably track it down (it may also be a boostrapping issue- it's using an already published version of cargo-dist- this is my guess anyway)

**Comment by tshepang** [comment]
this is after the changes made in above-mentioned pr
```
❯ rg 2023 cargo-dist --files-with-matches
cargo-dist/tests/snapshots/axolotlsay_no_homebrew_publish.snap
cargo-dist/tests/snapshots/axolotlsay_musl_no_gnu.snap
cargo-dist/tests/snapshots/axolotlsay_updaters.snap
cargo-dist/tests/snapshots/axolotlsay_basic_lies.snap
cargo-dist/tests/snapshots/axolotlsay_abyss.snap
cargo-dist/tests/snapshots/axolotlsay_user_host_job.snap
cargo-dist/tests/snapshots/axolotlsay_user_local_build_job.snap
cargo-dist/tests/snapshots/axolotlsay_basic.snap
cargo-dist/tests/snapshots/axolotlsay_user_global_build_job.snap
cargo-dist/tests/snapshots/axolotlsay_user_publish_job.snap
cargo-dist/tests/snapshots/axolotlsay_edit_existing.snap
cargo-dist/tests/snapshots/axolotlsay_homebrew_packages.snap
cargo-dist/tests/snapshots/axolotlsay_abyss_only.snap
cargo-dist/tests/snapshots/axolotlsay_user_plan_job.snap
cargo-dist/tests/snapshots/axolotlsay_musl.snap

**Comment by mistydemeo** [comment]
Merged; thanks very much for the PR!

**Comment by mistydemeo** [comment]
I took a look at the remaining dates from the other snapshots, and it looks like those copyright years are from the external repos that we're testing cargo-dist against. We're specifically pulling versions of those packages that were released in 2023, so the 2023 year is correct for those specific commits. That said, we should make sure to update axolotlsay for newer versions.

**Comment by tshepang** [comment]
LICENSE-MIT and LICENSE-APACHE also need an update, and I paused because they got 2023 on them, instead of 2022, the year the repo was created.

**Comment by mistydemeo** [comment]
Those'll get updated in #884.
