### ISSUE TITLE
Use "GitHub" over "Github"

### ISSUE THREAD

**Issue by tisonkun** [axodotdev/cargo-dist#885]
It seems the automation checks text content identical, and I found my typo fixing on the generated "release.yml" cause pipeline to fail:

https://github.com/korandoru/hawkeye/actions/runs/8460335170/job/23178340096?pr=133

Hopefully it should be fixed in a template file in this repo. But I don't know which one is the template. I'm willing to send a patch to fix it if it's desired.

**Comment by mistydemeo** [comment]
Thanks for offering to fix it! The template is here: https://github.com/axodotdev/cargo-dist/blob/main/cargo-dist/templates/ci/github_ci.yml.j2

**Comment by tisonkun** [comment]
Patch sent - https://github.com/axodotdev/cargo-dist/pull/886

BTW, I found the skipped job has an unresolved name, is it possible to improve?

<img width="915" alt="image" src="https://github.com/axodotdev/cargo-dist/assets/18818196/33683c38-dbc0-4f14-a993-54685057c99a">

Actually, I don't check carefully the generated workflow but give it a fire to see first 🤣
