### ISSUE TITLE
Warnings get caught in the manifest

### ISSUE THREAD

**Issue by DCNick3** [axodotdev/cargo-dist#90]
In github action if a warning is emitted during `cargo dist`, it is still captured and stored into `dist-manifest.json`, producing and invalid json.

One solution would be to redirect logging to stderr, or to disable it when doing json output

Example of such a manifest: https://gist.github.com/DCNick3/dd76529acfb7eac240ff19d6dcee86a0

**Comment by DCNick3** [comment]
Still interested what the workaround might be

**Comment by Gankra** [comment]
Oh weird the warn was supposed to go to stderr, my bad!
