### ISSUE TITLE
CI: Vary swatinem/rust-cache key by target

### ISSUE THREAD

**Issue by connec** [axodotdev/cargo-dist#907]
I've noticed that the `swatinem/rust-cache` step generates the same key for different targets. Ultimately this leads to low hit rates since the cache will only be valid for a single local artifact job.

| aarch64-unknown-linux-gnu | x86_64-unknown-linux-musl |
| - | - |
| <img width="750" alt="image" src="https://github.com/axodotdev/cargo-dist/assets/160652/d6f10bd2-b550-491d-9978-342c7e5b4bd1"> | <img width="754" alt="image" src="https://github.com/axodotdev/cargo-dist/assets/160652/d8001d19-b124-4f6d-8683-ad490fe634f4"> |

One option would be to use the `key` input (see [docs](https://github.com/Swatinem/rust-cache?tab=readme-ov-file#example-usage)) with `matrix.targets`, `matrix.dist_args`, or a hash thereof (I'm not sure which would be more appropriate). E.g.

https://github.com/axodotdev/cargo-dist/blob/a2a599e8682e7927a4e1e96198ac4400de4b1bca/cargo-dist/templates/ci/github_ci.yml.j2#L176

Becomes:

```yaml
      - uses: swatinem/rust-cache@v2
        with:
          key: ${{ join(matrix.targets, '-') }}
```

This would inflate cache sizes, but lead to better hit rates.

**Comment by Gankra** [comment]
*Fascinating*, this would explain *a lot*. I'll look into this...

**Comment by mistydemeo** [comment]
Done; this'll be in the next release. Thank you for bringing this to our attention!
