### ISSUE TITLE
Installers in workspaces do not seem to work correctly

### ISSUE THREAD

**Issue by DCNick3** [axodotdev/cargo-dist#91]
When using an installer a in workspace with multiple binary crates, generating an installer does... weird things

Mostly this is due to all generated artifacts having name `installer.sh`

Locally, the `installer.sh` is overridden by one of the apps, creating an installer for just one of them

In github actions it results in `404: Not Found` with one of the installers uploaded. I guess this is HTTP speak for "already exists"?

A simple solution would be to add an app name prefix to the generated installer if multiple installers are built. Probably links in release description will have to be adjusted too...

**Comment by Gankra** [comment]
Oh yes, great point! Do you have a specific multi-binary workspace you can share? I've been waiting for someone with that kind of setup to chime in so I know what behaviours they want (see also #69).

**Comment by DCNick3** [comment]
Sure! https://github.com/DCNick3/shin

It has a CLI tool and a game. I probably want them to have different installers, as the audiences are different.

I can imagine wanting to have one installer for multiple binaries though

**Comment by Gankra** [comment]
working on a more holistic fix to this in #111
