### ISSUE TITLE
Allow to select which binaries should be build & published

### ISSUE THREAD

**Issue by DCNick3** [axodotdev/cargo-dist#93]
I have a workspace (https://github.com/DCNick3/shin) with a binary that is used mostly for write-once experiments (called `junk`), so I don't want it in my builds & releases.

I am already excluding it from `cargo-release` with `release = false` in `[package.metadata.release]` in `Cargo.toml`. It would be nice to have such an option in `cargo-dist` too

**Comment by Gankra** [comment]
Is #79 an acceptable solution for your usecase?

**Comment by DCNick3** [comment]
No. I currently have some git dependencies (because stuff is not merged yet), so I can't really publish to crates.io

A hint would be nice though

**Comment by kujeger** [comment]
There's `default-members`in `[workspace]` which determines which members/packages are built or run by default when using e.g. `cargo build` -- perhaps cargo-dist could use the same behaviour?
