### ISSUE TITLE
Release artifact jobs build entire workspace when only a single package was released

### ISSUE THREAD

**Issue by mstange** [axodotdev/cargo-dist#936]
In [this job for the samply-v0.12.0 release](https://github.com/mstange/samply/actions/runs/8697926896/job/23854074840), I can see that it's building `benchmarks` and `wholesym-addr2line`, which are two members of my workspace which have `publish = false` in their Cargo.toml. These compilations added quite a bit of extra time to this job. Can they be skipped?

**Comment by Gankra** [comment]
This should be an ideal case for https://opensource.axo.dev/cargo-dist/book/reference/config.html#precise-builds

**Comment by mstange** [comment]
Perfect, thank you. I've added it to my config and will give it a try on the next release.
