### ISSUE TITLE
teach shell installer to properly setup paths/rcfiles for fish shell

### ISSUE THREAD

**Issue by Gankra** [axodotdev/cargo-dist#946]
Some good references:

* rustup rust impl (what our current impl is based on for other shells):
  * https://github.com/rust-lang/rustup/blob/master/src/cli/self_update/shell.rs#L209-L211
  * https://github.com/rust-lang/rustup/blob/master/src/cli/self_update/env.fish
* grit shell impl (backup/cross-reference):
  *  https://docs.grit.io/install

**Comment by mistydemeo** [comment]
I use fish, so I'm happy to do this and make myself the guinea pig.

**Comment by Gankra** [comment]
done in #958
