### ISSUE TITLE
Bug: shell installer tries to fetch wrong binaries on Windows

### ISSUE THREAD

**Issue by mistydemeo** [axodotdev/cargo-dist#982]
On Windows, the shell installer unconditionally tries to fetch binaries for "pc-windows-gnu", but cargo-dist itself never builds for that triple. We inherited this logic from rustup, which *does* publish binaries for both `pc-windows-gnu` and `pc-windows-msvc`. We should adjust this to be aware of msvc binaries, and to perform a similar fallback logic as in other paths if `pc-windows-gnu` is picked but only `pc-windows-msvc` binaries are present.

**Comment by Gankra** [comment]
fixed by #984
